import { useMemo,useState } from 'react'
import { ArrowLeft, MessageCircle, Minus, Plus, ShoppingCart, Trash2 } from 'lucide-react'
import { Link, Navigate } from 'react-router-dom'
import { useAppData } from '../context/AppDataContext'
import { money } from '../utils/commerce'

export default function CartPage(){
  const {data,loading,cart,updateCartQuantity,removeFromCart}=useAppData()
  const items=useMemo(()=>data?cart.map(row=>{const p=data.products.find(x=>x.id===row.productId);return p?{...p,quantity:row.quantity,subtotal:p.price*row.quantity}:null}).filter(Boolean):[],[data,cart]); const total=items.reduce((s,x)=>s+x.subtotal,0)
  if(loading)return <div className="screen-loader">Cargando carrito…</div>; if(!data.settings.storeEnabled)return <Navigate to="/" replace/>
  return <section className="page-section surface-section"><div className="container"><div className="page-hero compact"><span className="section-kicker">Tu compra</span><h1>Carrito</h1><p>Los precios publicados son los generales para tarjeta/Mercado Pago. En retiro, efectivo o transferencia obtienen 10% de descuento.</p></div>
  {!items.length?<div className="empty-cart"><ShoppingCart size={36}/><h2>Tu carrito está vacío</h2><p>Agregá productos desde el catálogo.</p><Link className="btn btn-primary" to="/store"><ArrowLeft size={17}/> Ver productos</Link></div>:<div className="cart-layout"><div className="cart-items">{items.map(x=><article className="cart-item" key={x.id}><img src={x.image} alt={x.name}/><div className="cart-item-copy"><small>{x.brand} · {x.sku}</small><h2>{x.name}</h2><span>{money(x.price)} c/u</span></div><div className="qty-control"><button onClick={()=>updateCartQuantity(x.id,x.quantity-1)}><Minus size={15}/></button><strong>{x.quantity}</strong><button disabled={x.quantity>=x.stock} onClick={()=>updateCartQuantity(x.id,x.quantity+1)}><Plus size={15}/></button></div><strong className="cart-line-total">{money(x.subtotal)}</strong><button className="danger-icon" onClick={()=>removeFromCart(x.id)}><Trash2 size={17}/></button></article>)}</div><aside className="checkout-card"><span className="section-kicker">Resumen</span><h2>Tu compra</h2><div className="checkout-summary"><div><span>Productos</span><strong>{items.reduce((s,x)=>s+x.quantity,0)}</strong></div><div className="checkout-total"><span>Subtotal</span><strong>{money(total)}</strong></div></div><div className="cart-payment-hint"><strong>Hasta 10% OFF</strong><span>en efectivo o transferencia con retiro en sucursal.</span></div><Link className="btn btn-primary full-width" to="/checkout">Continuar compra</Link><small className="checkout-note">En el siguiente paso elegís retiro/envío, completás tus datos y seleccionás el medio de pago.</small></aside></div>}</div></section>
}