import { useMemo,useState } from 'react'
import { ArrowLeft, MessageCircle, Minus, Plus, ShoppingCart, Trash2 } from 'lucide-react'
import { Link, Navigate } from 'react-router-dom'
import { useAppData } from '../context/AppDataContext'
import { money } from '../utils/commerce'

export default function CartPage(){
  const {data,loading,cart,updateCartQuantity,removeFromCart,createOrder}=useAppData(); const [form,setForm]=useState({name:'',phone:'',notes:''}); const [sending,setSending]=useState(false); const [created,setCreated]=useState(null)
  const items=useMemo(()=>data?cart.map(row=>{const p=data.products.find(x=>x.id===row.productId); return p?{...p,quantity:row.quantity,subtotal:p.price*row.quantity}:null}).filter(Boolean):[],[data,cart]); const total=items.reduce((s,x)=>s+x.subtotal,0)
  if(loading)return <div className="screen-loader">Cargando pedido…</div>; if(!data.settings.storeEnabled)return <Navigate to="/" replace/>
  const submit=async e=>{e.preventDefault(); if(!items.length)return; setSending(true); const order=await createOrder({customerName:form.name,phone:form.phone,notes:form.notes,items:items.map(x=>({productId:x.id,quantity:x.quantity}))}); setCreated(order); const lines=order.items.map(x=>`• ${x.quantity} x ${x.name} - ${money(x.subtotal)}`); const text=`Hola RC Repuestos, quiero solicitar el pedido ${order.publicCode}:\n\n${lines.join('\n')}\n\nTotal estimado: ${money(order.total)}\nNombre: ${form.name}\nTeléfono: ${form.phone}${form.notes?`\nNota: ${form.notes}`:''}\n\nQuedo a la espera de confirmación de disponibilidad, compatibilidad y total final.`; window.open(`https://wa.me/${data.settings.whatsapp}?text=${encodeURIComponent(text)}`,'_blank','noopener,noreferrer'); setSending(false)}
  if(created)return <section className="page-section surface-section"><div className="container narrow-container"><div className="order-success"><MessageCircle size={34}/><span className="section-kicker">Pedido enviado</span><h1>{created.publicCode}</h1><p>El pedido quedó registrado y abrimos WhatsApp con el detalle. El stock todavía no se descuenta: el negocio debe revisar y confirmar la venta.</p><div className="order-success-total"><span>Total estimado</span><strong>{money(created.total)}</strong></div><Link className="btn btn-primary" to="/store">Volver a la tienda</Link></div></div></section>
  return <section className="page-section surface-section"><div className="container"><div className="page-hero compact"><span className="section-kicker">Tu pedido</span><h1>Pedido de compra</h1><p>Revisá cantidades y enviá la solicitud por WhatsApp. El pedido no reserva stock hasta que el negocio lo confirme.</p></div>
    {!items.length?<div className="empty-cart"><ShoppingCart size={36}/><h2>Tu pedido está vacío</h2><p>Agregá productos desde la tienda.</p><Link className="btn btn-primary" to="/store"><ArrowLeft size={17}/> Ver productos</Link></div>:<div className="cart-layout"><div className="cart-items">{items.map(x=><article className="cart-item" key={x.id}><img src={x.image} alt={x.name}/><div className="cart-item-copy"><small>{x.brand} · {x.sku}</small><h2>{x.name}</h2><span>{money(x.price)} c/u</span></div><div className="qty-control"><button onClick={()=>updateCartQuantity(x.id,x.quantity-1)}><Minus size={15}/></button><strong>{x.quantity}</strong><button disabled={x.quantity>=x.stock} onClick={()=>updateCartQuantity(x.id,x.quantity+1)}><Plus size={15}/></button></div><strong className="cart-line-total">{money(x.subtotal)}</strong><button className="danger-icon" onClick={()=>removeFromCart(x.id)}><Trash2 size={17}/></button></article>)}</div>
      <aside className="checkout-card"><span className="section-kicker">Solicitud</span><h2>Datos de contacto</h2><form onSubmit={submit}><label><span>Nombre completo</span><input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label><span>Celular / WhatsApp</span><input required value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></label><label><span>Observaciones</span><textarea value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})} placeholder="Ej. retiro por la tarde"/></label><div className="checkout-summary"><div><span>Productos</span><strong>{items.reduce((s,x)=>s+x.quantity,0)}</strong></div><div className="checkout-total"><span>Total estimado</span><strong>{money(total)}</strong></div></div><button className="btn btn-primary full-width" disabled={sending}><MessageCircle size={18}/> {sending?'Preparando…':'Enviar pedido por WhatsApp'}</button><small className="checkout-note">El negocio puede ajustar el pedido si hubo una venta presencial todavía no registrada.</small></form></aside></div>}
  </div></section>
}
