import { useEffect,useMemo,useState } from 'react'
import { Check, Search, ShoppingCart, SlidersHorizontal, X } from 'lucide-react'
import { Link, useSearchParams } from 'react-router-dom'
import { useAppData } from '../context/AppDataContext'
import { money } from '../utils/commerce'

export default function StorePage(){
  const {data,loading,addToCart,cart}=useAppData(); const [params]=useSearchParams(); const [query,setQuery]=useState(params.get('q')||''); const [category,setCategory]=useState(params.get('categoria')||'Todos'); const [subcategory,setSubcategory]=useState('Todos'); const [brand,setBrand]=useState('Todas'); const [mobileFilters,setMobileFilters]=useState(false); const [added,setAdded]=useState(null)
  useEffect(()=>{setQuery(params.get('q')||'');setCategory(params.get('categoria')||'Todos')},[params])
  const subcategories=useMemo(()=>{if(!data)return[]; if(category==='Todos')return[...new Set(data.productCategories.flatMap(x=>x.active?x.subcategories.filter(s=>s.active).map(s=>s.name):[]))]; return data.productCategories.find(x=>x.name===category)?.subcategories.filter(x=>x.active).map(x=>x.name)||[]},[data,category])
  const filtered=useMemo(()=>data?data.products.filter(x=>x.active).filter(x=>category==='Todos'||x.category===category).filter(x=>subcategory==='Todos'||x.subcategory===subcategory).filter(x=>brand==='Todas'||x.brand===brand).filter(x=>!query.trim()||`${x.name} ${x.brand} ${x.category} ${x.subcategory} ${x.sku} ${x.compatibility||''} ${x.oemCode||''}`.toLowerCase().includes(query.toLowerCase())):[],[data,query,category,subcategory,brand])
  if(loading)return <div className="screen-loader">Cargando catálogo…</div>
  const clear=()=>{setQuery('');setCategory('Todos');setSubcategory('Todos');setBrand('Todas')}
  const add=product=>{addToCart(product.id);setAdded(product.id);setTimeout(()=>setAdded(null),900)}
  return <section className="rc-catalog-page"><div className="container"><div className="rc-catalog-hero"><span>CATÁLOGO RC</span><h1>Encontrá el repuesto correcto.</h1><p>Buscá por nombre, código, marca o modelo. Antes de confirmar tu compra revisamos compatibilidad y disponibilidad real.</p></div>
    <div className="rc-catalog-search"><Search size={20}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Ej. pastillas Wave 110, NGK, 6302, CG 150…"/><button className="rc-filter-mobile" onClick={()=>setMobileFilters(x=>!x)}><SlidersHorizontal size={18}/> Filtros</button></div>
    <div className="rc-store-layout"><aside className={`rc-store-sidebar ${mobileFilters?'show-mobile':''}`}><div className="rc-filter-title"><strong>Filtrar productos</strong><button onClick={clear}><X size={14}/> Limpiar</button></div><label><span>Categoría</span><select value={category} onChange={e=>{setCategory(e.target.value);setSubcategory('Todos')}}><option>Todos</option>{data.productCategories.filter(x=>x.active).map(x=><option key={x.id}>{x.name}</option>)}</select></label><label><span>Subcategoría</span><select value={subcategory} onChange={e=>setSubcategory(e.target.value)}><option>Todos</option>{subcategories.map(x=><option key={x}>{x}</option>)}</select></label><label><span>Marca</span><select value={brand} onChange={e=>setBrand(e.target.value)}><option>Todas</option>{data.brands.filter(x=>x.active).map(x=><option key={x.id}>{x.name}</option>)}</select></label><div className="rc-filter-note"><strong>¿No sabés cuál lleva?</strong><p>Buscá por modelo o mandanos una foto/código por WhatsApp. Confirmamos aplicación antes de vender.</p></div></aside>
      <div className="rc-products-area"><div className="rc-results"><strong>{filtered.length} productos</strong><Link to="/carrito"><ShoppingCart size={16}/> Mi pedido ({cart.reduce((s,x)=>s+x.quantity,0)})</Link></div><div className="rc-products-grid">{filtered.map(product=><article className="rc-product-card" key={product.id}><div className="rc-product-image"><img src={product.image} alt={product.name}/><span className="rc-product-brand">{product.brand}</span>{product.featured&&<span className="rc-product-featured">DESTACADO</span>}</div><div className="rc-product-body"><small>{product.category} · {product.subcategory}</small><h2>{product.name}</h2><div className="rc-product-compat"><span>APLICACIÓN</span><strong>{product.compatibility||'Consultar compatibilidad'}</strong>{product.oemCode&&<small>Ref. {product.oemCode}</small>}</div><div className="rc-product-stock"><span className={product.stock<=product.minStock?'low':''}>{product.stock>0?'Disponible':'Sin stock'}</span><small>SKU {product.sku}</small></div><div className="rc-product-price"><span>Precio</span><strong>{data.settings.showPrices?money(product.price):'Consultar'}</strong></div><button className="rc-add-btn" disabled={product.stock<=0} onClick={()=>add(product)}>{added===product.id?<><Check size={18}/> Agregado</>:<><ShoppingCart size={18}/> Agregar al pedido</>}</button></div></article>)}</div></div></div>
  </div></section>
}
