import { useEffect,useMemo,useState } from 'react'
import { Check, Search, ShoppingCart, SlidersHorizontal, X } from 'lucide-react'
import { Link, useSearchParams } from 'react-router-dom'
import { useAppData } from '../context/AppDataContext'
import { money } from '../utils/commerce'
const catalogPrice=p=>{const values=(p.variants||[]).filter(v=>v.active&&v.available&&Number(v.price)>0).map(v=>Number(v.price));if(!values.length)return null;const list=(p.variants||[]).filter(v=>v.active&&v.available&&Number(v.listPrice)>0).map(v=>Number(v.listPrice));return{min:Math.min(...values),max:Math.max(...values),listMin:list.length?Math.min(...list):Math.min(...values),listMax:list.length?Math.max(...list):Math.max(...values)}}

export default function StorePage(){
  const {data,loading,catalogState,catalogError,retryPublicCatalog,addToCart,cart}=useAppData(); const [params]=useSearchParams(); const [query,setQuery]=useState(params.get('q')||''); const [category,setCategory]=useState(params.get('categoria')||'Todos'); const [subcategory,setSubcategory]=useState(params.get('subcategoria')||'Todos'); const [brand,setBrand]=useState('Todas'); const [mobileFilters,setMobileFilters]=useState(false); const [added,setAdded]=useState(null)
  useEffect(()=>{setQuery(params.get('q')||'');setCategory(params.get('categoria')||'Todos');setSubcategory(params.get('subcategoria')||'Todos')},[params])
  const subcategories=useMemo(()=>{if(!data)return[]; if(category==='Todos')return[...new Set(data.productCategories.flatMap(x=>x.active?x.subcategories.filter(s=>s.active).map(s=>s.name):[]))]; return data.productCategories.find(x=>x.name===category)?.subcategories.filter(x=>x.active).map(x=>x.name)||[]},[data,category])
  const filtered=useMemo(()=>data?data.products.filter(x=>x.active).filter(x=>category==='Todos'||x.category===category).filter(x=>subcategory==='Todos'||x.subcategory===subcategory).filter(x=>brand==='Todas'||x.brand===brand).filter(x=>!query.trim()||`${x.name} ${x.brand} ${x.category} ${x.subcategory} ${x.sku} ${x.compatibility||''} ${x.oemCode||''}`.toLowerCase().includes(query.toLowerCase())):[],[data,query,category,subcategory,brand])
  if(loading)return <div className="screen-loader">Cargando catálogo…</div>
  if(catalogState==='error')return <section className="rc-catalog-page"><div className="container"><div className="admin-login-card"><h1>No pudimos cargar el catálogo</h1><p>{catalogError}</p><button className="btn btn-primary" onClick={retryPublicCatalog}>Reintentar</button></div></div></section>
  const clear=()=>{setQuery('');setCategory('Todos');setSubcategory('Todos');setBrand('Todas')}
  const add=product=>{addToCart(product.id);setAdded(product.id);setTimeout(()=>setAdded(null),900)}
  return <section className="rc-catalog-page"><div className="container"><div className="rc-catalog-hero"><span>CATÁLOGO RC</span><h1>Encontrá el repuesto correcto.</h1><p>Buscá por nombre, código, marca o modelo. Antes de confirmar tu compra revisamos compatibilidad y disponibilidad real.</p></div>
    <div className="rc-catalog-search"><Search size={20}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Ej. pastillas Wave 110, NGK, 6302, CG 150…"/><button className="rc-filter-mobile" onClick={()=>setMobileFilters(x=>!x)}><SlidersHorizontal size={18}/> Filtros</button></div>
    <div className="rc-store-layout"><aside className={`rc-store-sidebar ${mobileFilters?'show-mobile':''}`}><div className="rc-filter-title"><strong>Filtrar productos</strong><button onClick={clear}><X size={14}/> Limpiar</button></div><label><span>Categoría</span><select value={category} onChange={e=>{setCategory(e.target.value);setSubcategory('Todos')}}><option>Todos</option>{data.productCategories.filter(x=>x.active).map(x=><option key={x.id}>{x.name}</option>)}</select></label><label><span>Subcategoría</span><select value={subcategory} onChange={e=>setSubcategory(e.target.value)}><option>Todos</option>{subcategories.map(x=><option key={x}>{x}</option>)}</select></label><label><span>Marca</span><select value={brand} onChange={e=>setBrand(e.target.value)}><option>Todas</option>{data.brands.filter(x=>x.active).map(x=><option key={x.id}>{x.name}</option>)}</select></label><div className="rc-filter-note"><strong>¿No sabés cuál lleva?</strong><p>Buscá por modelo o mandanos una foto/código por WhatsApp. Confirmamos aplicación antes de vender.</p></div></aside>
      <div className="rc-products-area"><div className="rc-results"><strong>{filtered.length} productos</strong><Link to="/carrito"><ShoppingCart size={16}/> Mi pedido ({cart.reduce((s,x)=>s+x.quantity,0)})</Link></div><div className="rc-products-grid">{filtered.length===0?<div className="admin-login-card"><h2>No hay productos disponibles</h2><p>El catálogo está conectado correctamente, pero todavía no hay productos que coincidan con la búsqueda.</p></div>:filtered.map(product=><article className="rc-product-card" key={product.id}><div className="rc-product-image">{product.image?<img src={product.image} alt={product.name} loading="lazy"/>:<div className="product-image-placeholder">Sin imagen</div>}<span className="rc-product-brand">{product.brand}</span>{product.offerActive?<span className="rc-product-featured offer">OFERTA</span>:product.featured&&<span className="rc-product-featured">DESTACADO</span>}</div><div className="rc-product-body"><small>{product.category} · {product.subcategory}</small><h2><Link to={`/producto/${product.slug||product.id}`}>{product.name}</Link></h2>{product.hasVariants&&<div className="rc-variant-summary">{product.variants.filter(v=>v.active&&v.available).slice(0,8).map(v=>v.color?<span className="rc-color-dot" key={v.id} title={v.color} aria-label={v.color} style={{background:v.colorHex||'#d5d9de'}}/>:<span className="rc-presentation-chip" key={v.id}>{[v.size,v.name].filter(Boolean).join(' · ')||v.sku}</span>)}</div>}<div className="rc-product-compat"><span>APLICACIÓN</span><strong>{product.compatibility||'Consultar compatibilidad'}</strong>{product.oemCode&&<small>Ref. {product.oemCode}</small>}</div><div className="rc-product-stock"><span className={Number(product.availableStock)<=0?'out':Number(product.availableStock)<=Number(product.minStock)?'low':''}>{Number(product.availableStock)>0?'Disponible':'Sin stock'}</span><small>SKU {product.sku}</small></div><div className="rc-product-price"><span>Precio</span>{(()=>{const cp=catalogPrice(product);if(!data.settings.showPrices||!cp)return <strong className="regular-current-price">Consultar</strong>;const hasOffer=product.offerActive&&Number(cp.listMin)>Number(cp.min);const normalLabel=cp.listMin===cp.listMax?money(cp.listMin):`Desde ${money(cp.listMin)}`;const effectiveLabel=cp.min===cp.max?money(cp.min):`Desde ${money(cp.min)}`;return <div className={`rc-product-price-line ${hasOffer?'has-offer':''}`}>{hasOffer&&<span className="offer-old-price">{normalLabel}</span>}<strong className={hasOffer?'offer-current-price':'regular-current-price'}>{effectiveLabel}</strong></div>})()}</div><Link className="rc-add-btn" to={`/producto/${product.slug||product.id}`}><ShoppingCart size={18}/> Ver producto</Link></div></article>)}</div></div></div>
  </div></section>
}
