import { apiFetch } from '../api/apiClient'

const n=value=>Number(value||0)
const mapVariant=v=>({id:v.id,name:v.nombre||'',color:v.colorNombre||'',colorHex:v.colorHex||'',size:v.talle||'',sku:v.sku||'',barcode:v.codigoBarras||'',costPrice:n(v.costo),listPrice:n(v.precio),offerPrice:n(v.precioOferta),offerActive:!!v.precioOferta&&n(v.precioOferta)>0&&n(v.precioOferta)<n(v.precio),price:!!v.precioOferta&&n(v.precioOferta)>0&&n(v.precioOferta)<n(v.precio)?n(v.precioOferta):n(v.precio),stock:n(v.stock),reserved:n(v.reservado),availableStock:n(v.stockDisponible??v.disponible),minStock:n(v.stockMinimo),active:v.activa!==false,available:v.disponibleVenta!==false,isDefault:!!v.esPredeterminada,image:v.imagenUrl||'',cloudflareImageId:v.imagenCloudflareId||null,removeImage:false})
export const mapProduct=p=>{const variants=(p.variantes||[]).map(mapVariant),main=variants.find(v=>v.isDefault&&v.active)||variants.find(v=>v.active)||variants[0]||{};return{id:p.id,name:p.nombre||'',slug:p.slug||'',description:p.descripcion||'',brandId:p.marcaId||null,brand:p.marca||'',categoryId:p.categoriaId||null,category:p.categoriaPadre||p.categoria||'',subcategory:p.categoriaPadre?p.categoria:'',oemCode:p.codigoOem||'',compatibility:p.compatibilidad||'',active:p.activo!==false,published:p.publicado!==false,featured:!!p.destacado,newArrival:!!p.novedad,offerActive:!!p.ofertaActiva&&variants.some(v=>v.offerActive),image:p.imagenPrincipalUrl||'',cloudflareImageId:p.imagenPrincipalCloudflareId||null,hasVariants:!!p.manejaVariantes,autoPrice:!!p.precioAutomatico,trackStock:p.controlaStock!==false,pricingSupplierId:p.proveedorPrecioId||null,applySupplierMarkup:p.aplicarMargenProveedor!==false,applyBrandMarkup:p.aplicarMargenMarca!==false,productMarkupPercent:n(p.margenAdicional),variants,sku:main.sku||'',barcode:main.barcode||'',costPrice:n(main.costPrice),listPrice:n(main.listPrice||main.price),offerPrice:n(main.offerPrice),price:n(main.price),stock:variants.reduce((s,v)=>s+n(v.stock),0),reserved:variants.reduce((s,v)=>s+n(v.reserved),0),availableStock:variants.filter(v=>v.active&&v.available).reduce((s,v)=>s+n(v.availableStock),0),minStock:variants.reduce((s,v)=>s+n(v.minStock),0)}}
const mapMasters=m=>{const raw=(m.categorias||[]).map(c=>({id:c.id,name:c.nombre,slug:c.slug,parentId:c.categoriaPadreId||null,parentName:c.categoriaPadre||'',order:c.orden||0,active:c.activa!==false})),roots=raw.filter(c=>!c.parentId);return{brands:(m.marcas||[]).map(x=>({id:x.id,name:x.nombre,slug:x.slug,logoUrl:x.logoUrl||'',defaultMarkupPercent:n(x.margenPredeterminado),active:x.activa!==false})),productCategories:roots.map(root=>({...root,subcategories:raw.filter(c=>c.parentId===root.id)})),allCategories:raw,suppliers:(m.proveedores||[]).map(x=>({id:x.id,name:x.nombre,taxId:x.cuit||'',phone:x.telefono||'',email:x.email||'',defaultMarkupPercent:n(x.margenPredeterminado),active:x.activo!==false}))}}
const toSaveRequest=product=>{
  const variants=(product.variants||[]).filter(v=>v.active!==false)
  // Una sola referencia comercial es una implementación interna, no una decisión de UX:
  // siempre viaja como principal. Con varias, preservamos una única selección.
  const defaultIndex=variants.length===1?0:Math.max(0,variants.findIndex(v=>v.isDefault))
  return {id:product.id||null,nombre:product.name?.trim(),descripcion:product.description||null,marcaId:product.brandId||null,categoriaId:product.categoryId,codigoOem:product.oemCode||null,compatibilidad:product.compatibility||null,precioAutomatico:!!product.autoPrice,controlaStock:product.trackStock!==false,activo:product.active!==false,publicado:product.published!==false,destacado:!!product.featured,novedad:!!product.newArrival,ofertaActiva:!!product.offerActive,proveedorPrecioId:product.pricingSupplierId||null,aplicarMargenProveedor:product.applySupplierMarkup!==false,aplicarMargenMarca:product.applyBrandMarkup!==false,margenAdicional:n(product.productMarkupPercent),imagenPrincipalCloudflareId:product.cloudflareImageId||null,quitarImagenPrincipal:!!product.removeImage,variantes:variants.map((v,i)=>({id:v.id||null,nombre:v.name||null,colorNombre:v.color||null,colorHex:v.colorHex||null,talle:v.size||null,sku:v.sku?.trim(),codigoBarras:v.barcode||null,costo:n(v.costPrice),precio:n(v.listPrice??v.price),precioOferta:product.offerActive?n(v.offerPrice):null,stock:n(v.stock),stockMinimo:n(v.minStock),esPredeterminada:i===defaultIndex,activa:true,disponible:v.available!==false,imagenCloudflareId:v.cloudflareImageId||null,quitarImagen:!!v.removeImage}))}
}
export const apiCatalogRepository={publicProducts:async()=>(await apiFetch('/api/public/catalogo/productos')).map(mapProduct),publicMasters:async()=>mapMasters(await apiFetch('/api/public/catalogo/maestros')),masters:async()=>mapMasters(await apiFetch('/api/admin/catalogo/maestros')),adminProducts:async()=>(await apiFetch('/api/admin/catalogo/productos')).map(mapProduct),saveProduct:async product=>mapProduct(await apiFetch('/api/admin/catalogo/productos',{method:'POST',body:JSON.stringify(toSaveRequest(product))})),setProductActive:(id,activo)=>apiFetch(`/api/admin/catalogo/productos/${id}/estado`,{method:'PATCH',body:JSON.stringify({activo})}),previewPricePolicy:x=>apiFetch('/api/admin/pricing/preview-policy',{method:'POST',body:JSON.stringify({cost:Number(x.cost||0),marcaId:x.brandId||null,proveedorId:x.supplierId||null,aplicarMargenProveedor:x.applySupplierMarkup!==false,aplicarMargenMarca:x.applyBrandMarkup!==false,margenAdicional:Number(x.productMarkupPercent||0)})}),scan:code=>apiFetch(`/api/admin/productos/scan?code=${encodeURIComponent(code)}`)}
