import { apiFetch } from '../api/apiClient'
const payName={1:'Efectivo',2:'Transferencia',3:'mercadopago',4:'Tarjeta',5:'Otro'}
const orderStatus={1:'received',2:'confirmed',3:'awaiting_payment',4:'ready_for_pickup',5:'pending_shipment',6:'shipped',7:'completed',8:'cancelled'}
const paymentStatus={1:'pending',2:'awaiting_transfer',3:'approved',4:'rejected',5:'refunded',6:'cancelled'}
const delivery={1:'pickup',2:'shipping'}
const stockType={1:'initial',2:'purchase',3:'sale',4:'adjustment_in',5:'adjustment_out',6:'reservation',7:'reservation_release',8:'reservation_consumed',9:'return'}
const direction={1:'in',2:'out'}
const defaultVariant=p=>(p.variants||[]).find(v=>v.isDefault)||(p.variants||[])[0]
const payApi=v=>String(v||'').toLowerCase().includes('transfer')?'Transferencia':String(v||'').toLowerCase().includes('mercado')?'MercadoPago':String(v||'').toLowerCase().includes('tarjeta')?'Tarjeta':'Efectivo'
export const operationsRepository={
 saveBrand:x=>apiFetch('/api/admin/maestros/marcas',{method:'POST',body:JSON.stringify({id:x.id||null,nombre:x.name,margenPredeterminado:Number(x.defaultMarkupPercent||0),activa:x.active!==false,logoCloudflareImageId:x.logoCloudflareImageId||null,quitarLogo:x.removeLogo===true})}),
 brandState:(id,active)=>apiFetch(`/api/admin/maestros/marcas/${id}/estado`,{method:'PATCH',body:JSON.stringify(active)}),
 saveCategory:x=>apiFetch('/api/admin/maestros/categorias',{method:'POST',body:JSON.stringify({id:x.id||null,nombre:x.name,categoriaPadreId:x.parentId||null,orden:Number(x.order||0),activa:x.active!==false})}),
 categoryState:(id,active)=>apiFetch(`/api/admin/maestros/categorias/${id}/estado`,{method:'PATCH',body:JSON.stringify(active)}),
 saveSupplier:x=>apiFetch('/api/admin/maestros/proveedores',{method:'POST',body:JSON.stringify({id:x.id||null,nombre:x.name,cuit:x.taxId||null,telefono:x.phone||null,email:x.email||null,direccion:x.address||null,observaciones:x.notes||null,margenPredeterminado:Number(x.defaultMarkupPercent||0),activo:x.active!==false})}),
 supplierState:(id,active)=>apiFetch(`/api/admin/maestros/proveedores/${id}/estado`,{method:'PATCH',body:JSON.stringify(active)}),
 inventory:(page=1,pageSize=5,q='')=>apiFetch(`/api/admin/inventario?page=${page}&pageSize=${pageSize}${q?`&q=${encodeURIComponent(q)}`:''}`),
 stockMovements:(page=1,pageSize=5)=>apiFetch(`/api/admin/inventario/movimientos?page=${page}&pageSize=${pageSize}`),
 adjustStock:(variantId,newStock,note)=>apiFetch('/api/admin/inventario/ajustes',{method:'POST',body:JSON.stringify({productoVarianteId:variantId,nuevaCantidad:Number(newStock),motivo:note})}),
 purchases:()=>apiFetch('/api/admin/comercio/compras'),
 purchaseHistory:(page=1,pageSize=5)=>apiFetch(`/api/admin/comercio/compras/historial?page=${page}&pageSize=${pageSize}`),
 purchaseById:id=>apiFetch(`/api/admin/comercio/compras/${id}`),
 createPurchase:x=>apiFetch('/api/admin/comercio/compras',{method:'POST',body:JSON.stringify({proveedorId:x.supplierId,numeroComprobante:x.invoiceNumber||null,metodoPago:payApi(x.paymentMethod),observaciones:x.notes||null,descuento:Number(x.discountAmount||0),items:x.items.map(i=>({productoVarianteId:i.variantId,cantidad:Number(i.quantity),costoListaUnitario:Number(i.unitCost),descuentoPorcentaje:0,descuentoImporte:0}))})}),
 sales:()=>apiFetch('/api/admin/comercio/ventas'),
 commercialStatistics:(days=30)=>apiFetch(`/api/admin/estadisticas/comerciales?days=${days}`),
 salesHistory:(page=1,pageSize=5,q='',source='all')=>apiFetch(`/api/admin/comercio/ventas/historial?page=${page}&pageSize=${pageSize}${q?`&q=${encodeURIComponent(q)}`:''}${source&&source!=='all'?`&source=${encodeURIComponent(source)}`:''}`),
 saleById:id=>apiFetch(`/api/admin/comercio/ventas/${id}`),
 createSale:(x,products)=>apiFetch('/api/admin/comercio/ventas',{method:'POST',body:JSON.stringify({clienteNombre:x.customerName||null,telefono:x.phone||null,metodoPago:payApi(x.paymentMethod),notas:x.notes||null,descuento:Number(x.discountAmount||0),items:x.items.map(i=>{const p=products.find(p=>String(p.id)===String(i.productId));const v=defaultVariant(p||{});return{productoVarianteId:i.variantId||v?.id,cantidad:Number(i.quantity),precioUnitario:Number(i.unitPrice||p?.price||0),descuento:0}})})}),
 cash:()=>apiFetch('/api/admin/caja/movimientos'), cashHistory:(page=1,pageSize=5,period='30',q='',category='all')=>apiFetch(`/api/admin/caja/movimientos/historial?page=${page}&pageSize=${pageSize}&period=${encodeURIComponent(period)}${q?`&q=${encodeURIComponent(q)}`:''}${category&&category!=='all'?`&category=${encodeURIComponent(category)}`:''}`), createCash:x=>apiFetch('/api/admin/caja/movimientos',{method:'POST',body:JSON.stringify({direccion:x.direction,categoria:x.category,metodoPago:payApi(x.paymentMethod),importe:Number(x.amount),referencia:x.reference||null,descripcion:x.concept||x.notes||null})}),
 orders:(page=1,pageSize=5,q='',status='all',delivery='all')=>apiFetch(`/api/admin/pedidos?page=${page}&pageSize=${pageSize}${q?`&q=${encodeURIComponent(q)}`:''}${status&&status!=='all'?`&status=${encodeURIComponent(status)}`:''}${delivery&&delivery!=='all'?`&delivery=${encodeURIComponent(delivery)}`:''}`), orderById:id=>apiFetch(`/api/admin/pedidos/${id}`), createOrder:x=>apiFetch('/api/public/pedidos',{method:'POST',body:JSON.stringify({clienteNombre:x.customerName,telefono:x.phone,email:x.email||null,notas:x.notes||null,metodoPago:payApi(x.paymentMethod),tipoEntrega:x.deliveryType==='shipping'?'Envio':'Retiro',direccion:x.shippingAddress?{provincia:x.shippingAddress.province,ciudad:x.shippingAddress.city,codigoPostal:x.shippingAddress.postalCode,calle:x.shippingAddress.street,numero:x.shippingAddress.number,piso:null,departamento:null,referencia:x.shippingAddress.notes||null}:null,items:x.items.map(i=>{const p=x.products?.find(p=>String(p.id)===String(i.productId));const v=defaultVariant(p||{});return{productoVarianteId:i.variantId||v?.id,cantidad:Number(i.quantity)}})})}),
 advanceOrder:id=>apiFetch(`/api/admin/pedidos/${id}/avanzar`,{method:'POST'}), cancelOrder:id=>apiFetch(`/api/admin/pedidos/${id}/cancelar`,{method:'POST'}), confirmPayment:id=>apiFetch(`/api/admin/pedidos/${id}/confirmar-pago`,{method:'POST'}), track:code=>apiFetch(`/api/public/pedidos/seguimiento/${encodeURIComponent(code)}`),
 pricingRules:()=>apiFetch('/api/admin/pricing/reglas'), saveProductPricing:(productId,percent)=>apiFetch(`/api/admin/pricing/productos/${productId}`,{method:'PUT',body:JSON.stringify({percent:Number(percent||0),active:Number(percent||0)>0})}), pricingPreview:(variantId,cost,supplierId=null)=>apiFetch('/api/admin/pricing/preview',{method:'POST',body:JSON.stringify({productoVarianteId:variantId,cost:Number(cost||0),proveedorId:supplierId||null})}),
 publicContent:()=>apiFetch('/api/public/contenido'), config:()=>apiFetch('/api/admin/configuracion'), banners:()=>apiFetch('/api/admin/banners'),
 saveConfig:items=>apiFetch('/api/admin/configuracion',{method:'POST',body:JSON.stringify(items)}), saveBanner:x=>apiFetch('/api/admin/banners',{method:'POST',body:JSON.stringify(x)}), deleteBanner:id=>apiFetch(`/api/admin/banners/${id}`,{method:'DELETE'}),
 mapPurchase:x=>({id:x.id,number:x.numero,supplierId:x.proveedorId,supplierName:x.proveedor,invoiceNumber:x.numeroComprobante,date:x.fecha,notes:x.observaciones,subtotal:Number(x.subtotal),discountAmount:Number(x.descuento),totalCost:Number(x.total),paymentMethod:payName[x.metodoPago]||'Otro',status:x.estado===2?'confirmed':'draft',createdAt:x.creadoEn,itemCount:Number(x.cantidadItems??x.items?.length??0),items:(x.items||[]).map(i=>({variantId:i.productoVarianteId,sku:i.sku,name:i.producto,variant:i.variante||'',quantity:Number(i.cantidad),listUnitCost:Number(i.costoListaUnitario),discountPercent:Number(i.descuentoPorcentaje),discountAmount:Number(i.descuentoImporte),unitCost:Number(i.costoNetoUnitario),subtotal:Number(i.subtotal)}))}),
 mapSale:x=>({id:x.id,number:x.numero,source:x.origen,orderId:x.pedidoId,customerName:x.clienteNombre,phone:x.telefono,paymentMethod:payName[x.metodoPago]||'Otro',notes:x.notas,items:(x.items||[]).map(i=>({variantId:i.productoVarianteId,sku:i.sku,name:i.producto,quantity:Number(i.cantidad),listUnitPrice:Number(i.precioLista),unitPrice:Number(i.precioUnitario),unitCost:Number(i.costoUnitario),discountAllocated:Number(i.descuento),subtotal:Number(i.subtotal)})),grossTotal:Number(x.subtotal),discountAmount:Number(x.descuento),total:Number(x.total),costTotal:Number(x.costoTotal),grossProfit:Number(x.total)-Number(x.costoTotal),createdAt:x.creadoEn}),
 mapStock:x=>({id:x.id,productId:x.productoId,variantId:x.productoVarianteId,sku:x.sku,productName:x.productoNombre,variant:[x.color,x.talle,x.varianteNombre].filter(Boolean).join(' · '),type:stockType[x.tipo]||'movement',quantity:Number(x.cantidad),stockBefore:Number(x.stockAnterior),stockAfter:Number(x.stockPosterior),reference:x.referencia,note:x.motivo,createdAt:x.creadoEn}),
 mapCash:x=>({id:x.id,direction:direction[x.direccion]||'in',category:x.categoria,concept:x.descripcion||x.categoria,amount:Number(x.importe),paymentMethod:payName[x.metodoPago]||'Otro',reference:x.referencia,sourceId:x.ventaId||x.compraId,createdAt:x.creadoEn}),
 mapOrder:x=>({id:x.id,publicCode:x.numero,trackingCode:x.trackingCode,customerName:x.clienteNombre,phone:x.telefono,email:x.email,notes:x.notas,status:orderStatus[x.estado]||'received',paymentStatus:paymentStatus[x.estadoPago]||'pending',paymentMethod:x.metodoPago===2?'transfer':x.metodoPago===3?'mercadopago':'cash',deliveryType:delivery[x.tipoEntrega]||'pickup',grossTotal:Number(x.subtotal),discountAmount:Number(x.descuento),total:Number(x.totalProductos),shippingCost:x.costoEnvio,shippingCostStatus:x.costoEnvioACoordinar?'to_agree':'defined',createdAt:x.creadoEn,shippingAddress:x.direccion?{province:x.direccion.provincia,city:x.direccion.ciudad,postalCode:x.direccion.codigoPostal,street:x.direccion.calle,number:x.direccion.numero,notes:x.direccion.referencia}:null,items:(x.items||[]).map(i=>({variantId:i.productoVarianteId,productId:i.productoVarianteId,name:i.productoNombreSnapshot,variant:i.varianteSnapshot||'',sku:i.skuSnapshot,quantity:Number(i.cantidad),unitPrice:Number(i.precioUnitario),subtotal:Number(i.subtotal)})),statusHistory:(x.historial||[]).map(h=>({status:orderStatus[h.estadoNuevo]||'received',at:h.creadoEn,label:h.motivo})),saleId:x.venta?.id||null,saleNumber:x.venta?.numero||null,saleCompletedAt:x.venta?.creadoEn||null})
}
