import { BadgeDollarSign, BarChart3, Boxes, ClipboardList, History, LayoutDashboard, LogOut, PackageSearch, ReceiptText, Settings, ShoppingCart, Store, Tags, Truck, WalletCards, X, Image } from 'lucide-react'
import { NavLink,useNavigate } from 'react-router-dom'
import { useAppData } from '../context/AppDataContext'
import BrandLogo from './BrandLogo'
import { ADMIN_LOGIN_PATH } from '../config/admin'
const Item=({to,icon:Icon,children,onClick})=><NavLink to={to} onClick={onClick}><Icon size={18}/><span>{children}</span></NavLink>
export default function AdminSidebar({open,onClose}){const navigate=useNavigate();const{data,logoutAdmin}=useAppData();if(!data)return null;const logout=async()=>{await logoutAdmin();navigate(ADMIN_LOGIN_PATH,{replace:true})};return <><div className={`admin-overlay ${open?'show':''}`} onClick={onClose}/><aside className={`admin-sidebar ${open?'sidebar-open':''}`}><div className="admin-brand admin-brand-logo-only"><BrandLogo compact/><button className="sidebar-close" onClick={onClose}><X size={20}/></button></div><nav>
<div className="admin-nav-group"><small>Operación</small><Item to="/admin/dashboard" icon={LayoutDashboard} onClick={onClose}>Dashboard</Item><Item to="/admin/pos" icon={ShoppingCart} onClick={onClose}>Punto de venta</Item><Item to="/admin/pedidos" icon={ClipboardList} onClick={onClose}>Pedidos</Item><Item to="/admin/ventas/historial" icon={ReceiptText} onClick={onClose}>Historial ventas</Item><Item to="/admin/caja" icon={WalletCards} onClick={onClose}>Caja</Item></div>
<div className="admin-nav-group"><small>Catálogo y stock</small><Item to="/admin/catalogo" icon={Tags} onClick={onClose}>Catálogo</Item><Item to="/admin/productos" icon={Boxes} onClick={onClose}>Productos</Item><Item to="/admin/inventario" icon={PackageSearch} onClick={onClose}>Inventario</Item><Item to="/admin/proveedores" icon={Truck} onClick={onClose}>Proveedores</Item><Item to="/admin/compras" icon={Store} onClick={onClose}>Nueva compra</Item><Item to="/admin/compras/historial" icon={History} onClick={onClose}>Historial compras</Item></div>
<div className="admin-nav-group"><small>Gestión</small><Item to="/admin/estadisticas" icon={BarChart3} onClick={onClose}>Estadísticas</Item><Item to="/admin/contenido" icon={Image} onClick={onClose}>Contenido web</Item><Item to="/admin/configuracion" icon={Settings} onClick={onClose}>Configuración</Item></div>
</nav><button className="logout-button" onClick={logout}><LogOut size={17}/><span>Cerrar sesión</span></button></aside></>}