import {useEffect,useMemo,useRef,useState} from 'react'
import {Check,ImagePlus,Layers3,Plus,Trash2,X} from 'lucide-react'
import {imageRepository} from '../repositories/imageRepository'
import {apiCatalogRepository} from '../repositories/apiCatalogRepository'

const key=()=>`${Date.now()}-${Math.random().toString(36).slice(2)}`
const newVariant=(isDefault=true)=>({localKey:key(),id:null,name:'',color:'',colorHex:'',size:'',sku:'',barcode:'',costPrice:0,price:0,listPrice:0,offerPrice:0,stock:0,minStock:0,isDefault,active:true,available:true,image:'',cloudflareImageId:null,removeImage:false,pendingFile:null,preview:''})
const empty={id:null,name:'',description:'',brandId:null,categoryId:null,oemCode:'',compatibility:'',active:true,published:true,featured:false,newArrival:false,offerActive:false,image:'',cloudflareImageId:null,removeImage:false,autoPrice:false,pricingSupplierId:null,applySupplierMarkup:true,applyBrandMarkup:true,productMarkupPercent:0,trackStock:true,variants:[newVariant()]}
const money=n=>new Intl.NumberFormat('es-AR',{style:'currency',currency:'ARS',maximumFractionDigits:0}).format(Number(n||0))
const normalize=list=>{const a=(list?.length?list:[newVariant()]).map(v=>({...newVariant(false),...v,localKey:v.localKey||key()}));const active=a.map((v,i)=>({v,i})).filter(x=>x.v.active!==false);if(active.length===1){a[active[0].i].isDefault=true;return a}const principal=(active.find(x=>x.v.isDefault)||active[0])?.i;return a.map((v,i)=>({...v,isDefault:v.active!==false&&i===principal}))}
const inferMode=list=>{const a=(list||[]).filter(v=>v.active!==false);const c=a.some(v=>v.color?.trim()),s=a.some(v=>v.size?.trim());return c&&s?'color-size':c?'color':s?'size':'presentation'}
const label=(v,i)=>[v.color,v.size,v.name].filter(Boolean).join(' · ')||`Variante ${i+1}`
const namedColors={negro:'#111111',rojo:'#d71920',azul:'#175cd3',verde:'#16803a',amarillo:'#f4c430',blanco:'#ffffff',gris:'#808080',plateado:'#c0c0c0',dorado:'#c89b3c',naranja:'#f97316',violeta:'#7c3aed',morado:'#7c3aed',rosa:'#ec4899',celeste:'#38bdf8',marron:'#7c4a2d',marrón:'#7c4a2d'}
const inferColorHex=name=>namedColors[String(name||'').trim().toLowerCase()]||''
const validHex=value=>/^#[0-9a-f]{6}$/i.test(String(value||''))

export default function ProductEditor({product,data,onClose,onSave}){
 const[form,setForm]=useState(empty),[mode,setMode]=useState('presentation'),[saving,setSaving]=useState(false),[error,setError]=useState(''),[pendingFile,setPendingFile]=useState(null),[preview,setPreview]=useState(''),[pricing,setPricing]=useState(false)
 const fileRef=useRef(null),lock=useRef(false),pricingSeq=useRef(0);const categories=useMemo(()=>data.allCategories?.length?data.allCategories:data.productCategories||[],[data])
 useEffect(()=>{const variants=normalize(product?.variants?.filter(v=>v.active!==false)||[newVariant()]);setForm(product?{...empty,...product,removeImage:false,variants}:{...empty,brandId:data.brands?.find(x=>x.active)?.id||null,categoryId:categories.find(x=>x.active&&x.parentId)?.id||categories.find(x=>x.active)?.id||null,variants});setMode(inferMode(variants));setPendingFile(null);setPreview('');setError('')},[product,data.brands,categories])
 const variants=normalize(form.variants),multi=variants.length>1,simple=variants[0],supplier=data.suppliers?.find(x=>String(x.id)===String(form.pricingSupplierId)),brand=data.brands?.find(x=>String(x.id)===String(form.brandId))
 const setV=(i,patch)=>setForm(f=>({...f,variants:normalize(f.variants.map((v,n)=>n===i?{...v,...patch}:v))}))
 const addVariant=()=>setForm(f=>({...f,variants:[...normalize(f.variants),newVariant(false)]}))
 const removeVariant=i=>{const v=form.variants[i];if(v?.preview)URL.revokeObjectURL(v.preview);setForm(f=>f.variants.length===1?f:{...f,variants:normalize(f.variants.filter((_,n)=>n!==i))})}
 const makeDefault=i=>setForm(f=>({...f,variants:f.variants.map((v,n)=>({...v,isDefault:n===i}))}))
 const changeMode=m=>{setMode(m);setForm(f=>({...f,variants:f.variants.map(v=>({...v,color:m.includes('color')?v.color:'',colorHex:m.includes('color')?v.colorHex:'',size:m.includes('size')?v.size:'',name:m==='presentation'?v.name:v.name}))}))}
 const validFile=file=>{if(!file)return false;if(!['image/jpeg','image/png','image/webp','image/avif'].includes(file.type)){setError('Usá imágenes JPG, PNG, WebP o AVIF.');return false}if(file.size>10*1024*1024){setError('Cada imagen puede pesar hasta 10 MB.');return false}return true}
 const chooseMain=file=>{if(!validFile(file))return;if(preview)URL.revokeObjectURL(preview);setPendingFile(file);setPreview(URL.createObjectURL(file));setForm(f=>({...f,removeImage:false}))}
 const chooseVariant=(i,file)=>{if(!validFile(file))return;const old=form.variants[i]?.preview;if(old)URL.revokeObjectURL(old);setV(i,{pendingFile:file,preview:URL.createObjectURL(file),removeImage:false})}
 const clearVariant=i=>{const old=form.variants[i]?.preview;if(old)URL.revokeObjectURL(old);setV(i,{pendingFile:null,preview:'',image:'',cloudflareImageId:null,removeImage:true})}
 const validate=t=>{if(!t.name.trim())return'Ingresá el nombre del producto.';if(!t.categoryId)return'Seleccioná una categoría.';const a=t.variants.filter(v=>v.active!==false);if(a.some(v=>!v.sku?.trim()))return'Cada referencia necesita un SKU.';if(a.some(v=>Number(v.costPrice)<=0))return'Cada referencia activa necesita un costo mayor a $0.';if(!t.autoPrice&&a.some(v=>Number(v.listPrice??v.price)<=0))return'Con precio manual, cada referencia necesita un precio mayor a $0.';if(t.offerActive&&a.some(v=>Number(v.offerPrice)<=0))return'Cada referencia activa necesita un precio de oferta mayor a $0.';if(t.offerActive&&a.some(v=>Number(v.offerPrice)>=Number(v.listPrice??v.price)))return'El precio de oferta debe ser menor al precio normal de cada referencia.';if(a.length>1&&mode.includes('color')&&a.some(v=>!v.color?.trim()))return'Completá el color de todas las variantes.';if(a.length>1&&mode.includes('color')&&a.some(v=>!validHex(v.colorHex)))return'Seleccioná el color visual de cada variante para mostrarlo correctamente en el catálogo.';if(a.length>1&&mode.includes('size')&&a.some(v=>!v.size?.trim()))return'Completá el talle/medida de todas las variantes.';if(a.length>1&&mode==='presentation'&&a.some(v=>!v.name?.trim()))return'Completá la presentación de todas las variantes.';if(a.length>1&&a.some(v=>!(v.preview||v.image)&&!v.pendingFile))return'Cada variante debe tener su propia imagen.';const sk=a.map(v=>v.sku.trim().toUpperCase());if(new Set(sk).size!==sk.length)return'Hay SKU repetidos.';if(a.length>1&&a.filter(v=>v.isDefault).length!==1)return'Elegí una variante principal.';return''}
 const refreshPrices=async()=>{if(!form.autoPrice)return;const a=form.variants.map((v,i)=>({v,i})).filter(x=>x.v.active!==false&&Number(x.v.costPrice)>0);if(!a.length)return;setPricing(true);try{const r=await Promise.all(a.map(x=>apiCatalogRepository.previewPricePolicy({cost:x.v.costPrice,brandId:form.brandId,supplierId:form.pricingSupplierId,applySupplierMarkup:form.applySupplierMarkup,applyBrandMarkup:form.applyBrandMarkup,productMarkupPercent:form.productMarkupPercent})));setForm(f=>({...f,variants:f.variants.map((v,i)=>{const p=a.findIndex(x=>x.i===i);return p<0?v:{...v,price:Number(r[p].roundedPrice??r[p].RoundedPrice??0),listPrice:Number(r[p].roundedPrice??r[p].RoundedPrice??0)}})}))}catch(e){setError(e.message||'No se pudo calcular el precio.')}finally{setPricing(false)}}
 useEffect(()=>{if(!form.autoPrice)return;const seq=++pricingSeq.current;const timer=setTimeout(async()=>{const active=form.variants.map((v,i)=>({v,i})).filter(x=>x.v.active!==false&&Number(x.v.costPrice)>0);if(!active.length)return;setPricing(true);try{const results=await Promise.all(active.map(x=>apiCatalogRepository.previewPricePolicy({cost:x.v.costPrice,brandId:form.brandId,supplierId:form.pricingSupplierId,applySupplierMarkup:form.applySupplierMarkup,applyBrandMarkup:form.applyBrandMarkup,productMarkupPercent:form.productMarkupPercent})));if(seq!==pricingSeq.current)return;setForm(f=>({...f,variants:f.variants.map((v,i)=>{const p=active.findIndex(x=>x.i===i);return p<0?v:{...v,price:Number(results[p].roundedPrice??results[p].RoundedPrice??0),listPrice:Number(results[p].roundedPrice??results[p].RoundedPrice??0)}})}));setError('')}catch(err){if(seq===pricingSeq.current)setError(err.message||'No se pudo previsualizar el precio automático.')}finally{if(seq===pricingSeq.current)setPricing(false)}},350);return()=>clearTimeout(timer)},[form.autoPrice,form.brandId,form.pricingSupplierId,form.applySupplierMarkup,form.applyBrandMarkup,form.productMarkupPercent,form.variants.map(v=>`${v.localKey}:${v.active!==false}:${v.costPrice}`).join('|')])
 const submit=async e=>{e.preventDefault();if(lock.current)return;const target={...form,variants:normalize(form.variants)};const problem=validate(target);if(problem){setError(problem);return}lock.current=true;setSaving(true);setError('');const uploaded=[];try{let payload={...target,variants:target.variants.map(v=>({...v}))};if(pendingFile){const u=await imageRepository.upload(pendingFile,'product',form.id||null);uploaded.push(u.imageId);payload.cloudflareImageId=u.imageId;payload.removeImage=false}for(let i=0;i<payload.variants.length;i++){const v=payload.variants[i];if(v.pendingFile){const u=await imageRepository.upload(v.pendingFile,'product-variant',v.id||form.id||null);uploaded.push(u.imageId);v.cloudflareImageId=u.imageId;v.removeImage=false}delete v.pendingFile;delete v.preview;delete v.localKey}await onSave(payload)}catch(e){for(const id of uploaded){try{await imageRepository.remove(id)}catch{}}setError(e.message||'No se pudo guardar el producto.')}finally{lock.current=false;setSaving(false)}}
 const mainShown=preview||(!form.removeImage?form.image:'')
 const fields=(v,i,isSimple=false)=><div className="rcv-fields">
   <label className="rcpe-field"><span>Presentación</span><input value={v.name||''} onChange={e=>setV(i,{name:e.target.value})} placeholder="Ej. unidad, 1L, kit"/></label>
   {!isSimple&&mode.includes('color')&&<div className="rcpe-field rcv-color-field"><span>Color *</span><div className="rcv-color-control"><input className="rcv-color-name" value={v.color||''} onChange={e=>{const color=e.target.value;setV(i,{color,colorHex:v.colorHex||inferColorHex(color)})}} placeholder="Ej. Negro"/><input className="rcv-color-picker" type="color" value={validHex(v.colorHex)?v.colorHex:'#111111'} onChange={e=>setV(i,{colorHex:e.target.value})} title="Color que verá el cliente"/><span className="rcv-color-hex">{validHex(v.colorHex)?v.colorHex.toUpperCase():'Elegir'}</span></div></div>}
   {!isSimple&&mode.includes('size')&&<label className="rcpe-field"><span>Talle / medida *</span><input value={v.size||''} onChange={e=>setV(i,{size:e.target.value})} placeholder="Ej. M, 22 mm"/></label>}
   <label className="rcpe-field"><span>SKU *</span><input value={v.sku||''} onChange={e=>setV(i,{sku:e.target.value})}/></label>
   <label className="rcpe-field"><span>Código de barras</span><input value={v.barcode||''} onChange={e=>setV(i,{barcode:e.target.value})} placeholder="Opcional"/></label>
   <label className="rcpe-field"><span>Costo de reposición *</span><input type="number" min="0.01" step="0.01" value={v.costPrice} onChange={e=>setV(i,{costPrice:e.target.value})}/></label>
   <label className="rcpe-field"><span>{form.autoPrice?'Precio calculado':'Precio de venta *'}</span><input type="number" min="0.01" step="0.01" readOnly={form.autoPrice} value={v.listPrice??v.price} onChange={e=>setV(i,{price:e.target.value,listPrice:e.target.value})}/></label>
   {form.offerActive&&<label className="rcpe-field rcv-offer-field"><span>Precio de oferta *</span><input type="number" min="0.01" step="0.01" value={v.offerPrice||''} onChange={e=>setV(i,{offerPrice:e.target.value})} placeholder="Menor al precio normal"/><small>Precio promocional final para esta referencia.</small></label>}
   <label className="rcpe-field"><span>Stock mínimo</span><input type="number" min="0" step="0.001" value={v.minStock} onChange={e=>setV(i,{minStock:e.target.value})}/></label>
   <label className="rcpe-field"><span>{v.id?'Stock actual':'Stock inicial'}</span><input type="number" min="0" step="0.001" disabled={!!v.id} value={v.stock} onChange={e=>setV(i,{stock:e.target.value})}/></label>
 </div>
 return <div className="modal-backdrop rcpe-backdrop"><section className="rcpe-modal rcv-modal"><header className="rcpe-header"><div><span>{form.id?'EDITAR PRODUCTO':'NUEVO PRODUCTO'}</span><h2>{form.id?(form.name||'Producto'):'Cargar producto'}</h2></div><button type="button" className="rcpe-close" onClick={onClose}><X size={20}/></button></header>
 <form className="rcpe-form" onSubmit={submit}><div className="rcpe-scroll">{error&&<div className="rcpe-error">{error}</div>}
 <section className="rcv-general"><aside className="rcpe-image-panel"><button type="button" className={`rcpe-image ${mainShown?'has-image':''}`} onClick={()=>fileRef.current?.click()}>{mainShown?<img src={mainShown} alt=""/>:<span><ImagePlus size={30}/><strong>Imagen general</strong><small>Se usa como respaldo</small></span>}</button><input ref={fileRef} hidden type="file" accept="image/*" onChange={e=>chooseMain(e.target.files?.[0])}/><button type="button" className="rcpe-link" onClick={()=>fileRef.current?.click()}>{mainShown?'Cambiar':'Seleccionar'} imagen</button></aside>
 <div className="rcpe-details"><label className="rcpe-field rcpe-span-2"><span>Nombre del producto *</span><input autoFocus value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label className="rcpe-field"><span>Marca</span><select value={form.brandId||''} onChange={e=>setForm({...form,brandId:e.target.value||null})}><option value="">Sin marca</option>{(data.brands||[]).filter(x=>x.active).map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label className="rcpe-field"><span>Categoría *</span><select value={form.categoryId||''} onChange={e=>setForm({...form,categoryId:e.target.value})}><option value="">Seleccionar</option>{categories.filter(x=>x.active).map(x=><option key={x.id} value={x.id}>{x.parentName?`${x.parentName} / `:''}{x.name}</option>)}</select></label><label className="rcpe-field"><span>OEM / referencia</span><input value={form.oemCode||''} onChange={e=>setForm({...form,oemCode:e.target.value})}/></label><label className="rcpe-field"><span>Compatibilidad</span><input value={form.compatibility||''} onChange={e=>setForm({...form,compatibility:e.target.value})}/></label><label className="rcpe-field rcpe-span-2"><span>Descripción</span><textarea rows="3" value={form.description||''} onChange={e=>setForm({...form,description:e.target.value})}/></label></div></section>
 <section className="rcv-section"><div className="rcpe-section-head"><div><h3>Política de precio</h3><span>El costo pertenece a cada referencia. La vista previa usa la misma política del servidor; al guardar, el backend vuelve a calcular y persiste el precio definitivo.</span></div>{form.autoPrice&&<button type="button" className="btn btn-secondary" onClick={refreshPrices} disabled={pricing}>{pricing?'Calculando…':'Actualizar precios'}</button>}</div><label className="rcpe-check rcv-auto"><input type="checkbox" checked={form.autoPrice} onChange={e=>setForm({...form,autoPrice:e.target.checked})}/><span><strong>Calcular precio automáticamente</strong><small>Se actualiza automáticamente al cambiar costo o márgenes. El backend es la autoridad final.</small></span></label>{form.autoPrice&&<div className="rcpe-pricing"><label className="rcpe-field"><span>Proveedor de referencia</span><select value={form.pricingSupplierId||''} onChange={e=>setForm({...form,pricingSupplierId:e.target.value||null})}><option value="">Sin proveedor</option>{(data.suppliers||[]).filter(x=>x.active).map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label className="rcpe-check"><input type="checkbox" checked={form.applySupplierMarkup!==false} disabled={!form.pricingSupplierId} onChange={e=>setForm({...form,applySupplierMarkup:e.target.checked})}/><span><strong>Margen proveedor</strong><small>{supplier?`${supplier.defaultMarkupPercent}%`:'Seleccioná proveedor'}</small></span></label><label className="rcpe-check"><input type="checkbox" checked={form.applyBrandMarkup!==false} disabled={!form.brandId} onChange={e=>setForm({...form,applyBrandMarkup:e.target.checked})}/><span><strong>Margen marca</strong><small>{brand?`${brand.defaultMarkupPercent}%`:'Sin marca'}</small></span></label><label className="rcpe-field"><span>Margen adicional %</span><input type="number" min="0" step="0.01" value={form.productMarkupPercent} onChange={e=>setForm({...form,productMarkupPercent:e.target.value})}/></label></div>}</section>
 <section className="rcv-section">{!multi?<><div className="rcpe-section-head"><div><h3>Venta e inventario</h3><span>Una referencia comercial. Podés convertirla en producto con variantes.</span></div><button type="button" className="btn btn-secondary" onClick={addVariant}><Layers3 size={15}/> Agregar variantes</button></div><div className="rcv-simple">{fields(simple,0,true)}<div className="rcv-summary"><b>{money(simple.costPrice)}</b><span>costo</span><b>{money(simple.listPrice??simple.price)}</b><span>venta</span></div></div></>:<><div className="rcpe-section-head rcv-variant-head"><div><h3>Variantes</h3><span>Cada variante tiene SKU, costo, precio, stock e imagen propios.</span></div><label className="rcpe-field rcv-mode"><span>Este producto varía por</span><select value={mode} onChange={e=>changeMode(e.target.value)}><option value="presentation">Presentación</option><option value="color">Color</option><option value="size">Talle / medida</option><option value="color-size">Color + talle / medida</option></select></label><button type="button" className="btn btn-secondary" onClick={addVariant}><Plus size={15}/> Agregar variante</button></div><div className="rcpe-variants">{variants.map((v,i)=>{const shown=v.preview||(!v.removeImage?v.image:'');return <article className={`rcpe-variant rcv-card ${v.isDefault?'is-default':''}`} key={v.localKey}><div className="rcpe-variant-top"><div className="rcpe-variant-title"><strong>{label(v,i)}</strong><span>{v.id?'Existente':'Nueva'}</span></div><button type="button" className={`rcpe-default ${v.isDefault?'selected':''}`} onClick={()=>makeDefault(i)}>{v.isDefault?<><Check size={13}/> Principal</>:'Usar como principal'}</button><button type="button" className="rcpe-icon-danger" onClick={()=>removeVariant(i)}><Trash2 size={15}/></button></div><div className="rcv-body"><div className="rcv-variant-image"><label className={shown?'has-image':''}>{shown?<img src={shown} alt={label(v,i)}/>:<span><ImagePlus size={24}/><b>Imagen de variante *</b><small>{mode.includes('color')?'Foto del color real':'Foto de esta referencia'}</small></span>}<input type="file" accept="image/jpeg,image/png,image/webp,image/avif" disabled={saving} onChange={e=>{chooseVariant(i,e.target.files?.[0]);e.target.value=''}}/></label>{v.pendingFile&&<small className="rcv-upload-ready"><Check size={12}/> Se subirá al guardar</small>}{shown&&<button type="button" className="rcpe-link" disabled={saving} onClick={()=>clearVariant(i)}>Quitar imagen</button>}</div>{fields(v,i,false)}</div><div className="rcpe-variant-bottom"><label className="rcpe-check"><input type="checkbox" checked={v.available!==false} onChange={e=>setV(i,{available:e.target.checked})}/><span><strong>Disponible para venta</strong></span></label><div className="rcv-totals"><span>Costo <b>{money(v.costPrice)}</b></span><span>Venta <b>{money(v.listPrice??v.price)}</b></span></div></div></article>})}</div></>}</section>
 <div className="rcpe-publish"><label className="rcpe-check"><input type="checkbox" checked={form.trackStock} onChange={e=>setForm({...form,trackStock:e.target.checked})}/><span><strong>Controlar stock</strong></span></label><label className="rcpe-check"><input type="checkbox" checked={form.active} onChange={e=>setForm({...form,active:e.target.checked})}/><span><strong>Activo</strong></span></label><label className="rcpe-check"><input type="checkbox" checked={form.published} onChange={e=>setForm({...form,published:e.target.checked})}/><span><strong>Publicado</strong></span></label><label className="rcpe-check"><input type="checkbox" checked={form.featured} onChange={e=>setForm({...form,featured:e.target.checked})}/><span><strong>Destacado</strong></span></label><label className="rcpe-check"><input type="checkbox" checked={form.newArrival} onChange={e=>setForm({...form,newArrival:e.target.checked})}/><span><strong>Novedad</strong><small>Aparece en Novedades del inicio.</small></span></label><label className="rcpe-check rcv-offer-toggle"><input type="checkbox" checked={form.offerActive} onChange={e=>setForm({...form,offerActive:e.target.checked})}/><span><strong>Oferta activa</strong><small>Muestra precio normal tachado + precio promocional.</small></span></label></div>
 </div><footer className="rcpe-footer"><button type="button" className="btn btn-secondary" onClick={onClose}>Cancelar</button><button type="submit" className="btn btn-primary" disabled={saving}>{saving?'Guardando…':form.id?'Guardar cambios':'Crear producto'}</button></footer></form></section></div>
}
