import { useEffect, useMemo, useState } from 'react'
import { Calculator, Plus, Trash2, X } from 'lucide-react'
import { calculatePriceBreakdown, money } from '../utils/commerce'

const empty={id:0,sku:'',oemCode:'',name:'',brand:'',supplier:'',category:'',subcategory:'',price:0,costPrice:0,stock:0,minStock:3,trackStock:true,autoPrice:true,pricingRules:[],size:'Unidad',compatibility:'',active:true,featured:false,image:'',description:''}
export default function ProductEditor({product,data,onClose,onSave}){
 const defaults={...empty,brand:data.brands.find(x=>x.active)?.name||'',supplier:data.suppliers?.find(x=>x.active)?.name||'',category:data.productCategories.find(x=>x.active)?.name||''}
 const inherited=p=>{const b=data.brands.find(x=>x.name===p.brand),s=data.suppliers?.find(x=>x.name===p.supplier);return [{id:'supplier',name:`Proveedor · ${s?.name||'Sin proveedor'}`,concept:'Margen proveedor',percent:Number(s?.defaultMarkupPercent||0),enabled:true,source:'supplier'},{id:'brand',name:`Marca · ${b?.name||'Sin marca'}`,concept:'Margen marca',percent:Number(b?.defaultMarkupPercent||0),enabled:true,source:'brand'}]}
 const normalize=p=>{const base={...defaults,...p};const existing=p?.pricingRules||[];const inheritedRules=inherited(base).map(r=>{const e=existing.find(x=>x.source===r.source||String(x.name||'').startsWith(r.source==='supplier'?'Proveedor':'Marca'));return e?{...r,...e}:r});const custom=existing.filter(x=>!['supplier','brand'].includes(x.source)&&!String(x.name||'').startsWith('Proveedor')&&!String(x.name||'').startsWith('Marca'));return {...base,pricingRules:[...inheritedRules,...custom]}}
 const [form,setForm]=useState(()=>normalize(product||defaults));useEffect(()=>setForm(normalize(product||defaults)),[product])
 const subs=useMemo(()=>data.productCategories.find(x=>x.name===form.category)?.subcategories.filter(x=>x.active)||[],[data.productCategories,form.category])
 const syncInherited=next=>{const inh=inherited(next);const custom=(next.pricingRules||[]).filter(x=>!['supplier','brand'].includes(x.source));return {...next,pricingRules:[...inh.map(r=>{const old=(next.pricingRules||[]).find(x=>x.source===r.source);return old?{...r,enabled:old.enabled,percent:old.percent}:r}),...custom]}}
 const rules=(form.pricingRules||[]).filter(x=>x.enabled!==false);const breakdown=calculatePriceBreakdown(form.costPrice,rules,data.settings?.priceRoundingStep||500,data.settings?.priceRoundingMode||'up')
 const updateRule=(id,patch)=>setForm({...form,pricingRules:form.pricingRules.map(r=>r.id===id?{...r,...patch}:r)});const addRule=()=>setForm({...form,pricingRules:[...form.pricingRules,{id:`custom-${Date.now()}`,name:'Ajuste manual',concept:'Margen adicional',percent:0,enabled:true,source:'product'}]});const removeRule=id=>setForm({...form,pricingRules:form.pricingRules.filter(r=>r.id!==id)})
 const submit=e=>{e.preventDefault();onSave({...form,costPrice:Number(form.costPrice),price:form.autoPrice?breakdown.roundedPrice:Number(form.price),minStock:Number(form.minStock),pricingRules:form.pricingRules.map(r=>({...r,percent:Number(r.percent)||0}))})}
 return <div className="modal-backdrop"><div className="modal modal-wide"><button className="modal-close" onClick={onClose}><X/></button><span className="section-kicker">{form.id?'Editar':'Nuevo'} producto</span><h2>{form.id?form.name:'Crear repuesto'}</h2><form className="editor-form" onSubmit={submit}><label><span>Nombre</span><input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><div className="form-grid"><label><span>Marca</span><select value={form.brand} onChange={e=>setForm(syncInherited({...form,brand:e.target.value}))}>{data.brands.filter(x=>x.active).map(x=><option key={x.id}>{x.name}</option>)}</select></label><label><span>Proveedor</span><select value={form.supplier} onChange={e=>setForm(syncInherited({...form,supplier:e.target.value}))}>{(data.suppliers||[]).filter(x=>x.active).map(x=><option key={x.id}>{x.name}</option>)}</select></label></div><div className="form-grid"><label><span>SKU</span><input required value={form.sku} onChange={e=>setForm({...form,sku:e.target.value})}/></label><label><span>OEM / referencia</span><input value={form.oemCode||''} onChange={e=>setForm({...form,oemCode:e.target.value})}/></label></div><div className="form-grid"><label><span>Categoría</span><select value={form.category} onChange={e=>setForm({...form,category:e.target.value,subcategory:''})}>{data.productCategories.filter(x=>x.active).map(x=><option key={x.id}>{x.name}</option>)}</select></label><label><span>Subcategoría</span><select value={form.subcategory} onChange={e=>setForm({...form,subcategory:e.target.value})}>{subs.map(x=><option key={x.id}>{x.name}</option>)}</select></label></div><label><span>Compatibilidad</span><input value={form.compatibility||''} onChange={e=>setForm({...form,compatibility:e.target.value})}/></label>
 <div className="pricing-box"><div className="pricing-box-head"><div><strong>Formación de precio configurable</strong><small>Cada producto puede heredar porcentajes de proveedor y marca, desactivarlos o sumar conceptos propios.</small></div><Calculator/></div><label><span>Costo actual</span><input type="number" min="0" value={form.costPrice} onChange={e=>setForm({...form,costPrice:e.target.value})}/></label><div className="advanced-rules">{form.pricingRules.map(r=><div className={`advanced-rule ${r.enabled===false?'disabled':''}`} key={r.id}><label className="rule-check"><input type="checkbox" checked={r.enabled!==false} onChange={e=>updateRule(r.id,{enabled:e.target.checked})}/></label><input value={r.concept||r.name} onChange={e=>updateRule(r.id,{concept:e.target.value,name:e.target.value})}/><div className="percent-input"><input type="number" step="0.01" value={r.percent} onChange={e=>updateRule(r.id,{percent:e.target.value})}/><span>%</span></div><small>{r.source==='supplier'?'Proveedor':r.source==='brand'?'Marca':'Producto'}</small>{r.source==='product'&&<button type="button" className="danger-icon" onClick={()=>removeRule(r.id)}><Trash2 size={15}/></button>}</div>)}</div><button type="button" className="btn btn-secondary" onClick={addRule}><Plus size={16}/> Agregar concepto / porcentaje</button><div className="price-result"><span>Precio publicado sugerido</span><strong>{money(breakdown.roundedPrice)}</strong><label><input type="checkbox" checked={form.autoPrice} onChange={e=>setForm({...form,autoPrice:e.target.checked})}/> Precio automático</label></div>{!form.autoPrice&&<label><span>Precio manual</span><input type="number" value={form.price} onChange={e=>setForm({...form,price:e.target.value})}/></label>}<div className="rounding-preview"><span>Costo: <strong>{money(form.costPrice)}</strong></span><span>Antes de redondear: <strong>{money(breakdown.rawPrice)}</strong></span><span>Final: <strong>{money(breakdown.roundedPrice)}</strong></span></div></div>
 <div className="form-grid"><label><span>Stock actual</span><input value={form.stock} disabled/></label><label><span>Stock mínimo</span><input type="number" value={form.minStock} onChange={e=>setForm({...form,minStock:e.target.value})}/></label></div><div className="form-grid"><label><span>Presentación</span><input value={form.size} onChange={e=>setForm({...form,size:e.target.value})}/></label><label><span>Imagen URL</span><input value={form.image} onChange={e=>setForm({...form,image:e.target.value})}/></label></div><label><span>Descripción</span><textarea value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><div className="toggle-row"><label><input type="checkbox" checked={form.trackStock} onChange={e=>setForm({...form,trackStock:e.target.checked})}/> Controlar stock</label><label><input type="checkbox" checked={form.active} onChange={e=>setForm({...form,active:e.target.checked})}/> Activo</label><label><input type="checkbox" checked={form.featured} onChange={e=>setForm({...form,featured:e.target.checked})}/> Destacado</label></div><button className="btn btn-primary full-width">Guardar producto</button></form></div></div>
}
