import { createContext,useCallback,useContext,useEffect,useMemo,useState } from 'react'
import { adminAuth } from '../api/apiClient'
import { ADMIN_LOGIN_PATH } from '../config/admin'
import { apiCatalogRepository } from '../repositories/apiCatalogRepository'
import { operationsRepository as ops } from '../repositories/operationsRepository'
import { siteConfig } from '../config'
const AppDataContext=createContext(null);const CART_KEY='rc-repuestos-y-accesorios-cart-v18'
const emptyData=()=>({settings:siteConfig,brands:[],productCategories:[],allCategories:[],suppliers:[],products:[],orders:[],purchases:[],sales:[],stockMovements:[],cashMovements:[],webContent:{banners:[],brandCarousel:[]}})
const friendly=(e,f)=>e?.kind==='network'?'No pudimos conectar con la API.':e?.message||f
const parseConfig=x=>{if(x.tipo==='boolean')return String(x.valor).toLowerCase()==='true';if(x.tipo==='number')return Number(x.valor);return x.valor}
const discountAmount=x=>x.discountType==='percent'?Number(x.grossTotal||0)*Number(x.discountValue||0)/100:x.discountType==='amount'?Number(x.discountValue||0):0
export function AppDataProvider({children}){
 const[data,setData]=useState(emptyData);const[catalogState,setCatalogState]=useState('loading');const[catalogError,setCatalogError]=useState('');const[adminState,setAdminState]=useState('checking');const[adminError,setAdminError]=useState('');const[cart,setCart]=useState(()=>{try{return JSON.parse(localStorage.getItem(CART_KEY)||'[]')}catch{return[]}})
 useEffect(()=>localStorage.setItem(CART_KEY,JSON.stringify(cart)),[cart])
 const loadPublicCatalog=useCallback(async()=>{setCatalogState('loading');try{const[products,masters,content]=await Promise.all([apiCatalogRepository.publicProducts(),apiCatalogRepository.publicMasters(),ops.publicContent().catch(()=>({}))]);const brands=masters.brands;const cats=masters.productCategories;setData(c=>({...c,products,brands,allCategories:masters.allCategories,productCategories:cats,settings:{...c.settings,...(content.configuracion||{})},webContent:{...c.webContent,banners:(content.banners||[]).map(b=>({id:b.id,active:b.activo,order:b.orden,title:b.titulo,subtitle:b.subtitulo,desktopImage:b.imagenDesktopUrl,mobileImage:b.imagenMobileUrl,desktopCloudflareImageId:b.imagenDesktopCloudflareId||null,mobileCloudflareImageId:b.imagenMobileCloudflareId||null,ctaLink:b.linkUrl})),brandCarousel:brands.map((b,i)=>({...b,order:i+1,searchQuery:b.name}))}}));setCatalogState('ready');setCatalogError('')}catch(e){setCatalogState('error');setCatalogError(friendly(e,'No se pudo cargar el catálogo.'))}},[])
 const refreshAdmin=useCallback(async()=>{const[masters,rawProducts,purchases,stockMovements,orders,banners,config,pricingRules]=await Promise.all([apiCatalogRepository.masters(),apiCatalogRepository.adminProducts(),ops.purchases(),ops.stockMovements(1,5),ops.orders(),ops.banners(),ops.config(),ops.pricingRules()]);const productRules=new Map((pricingRules||[]).filter(x=>Number(x.tipo)===3&&x.productoId).map(x=>[String(x.productoId),Number(x.porcentaje||0)]));const products=rawProducts;const settings=Object.fromEntries((config||[]).map(x=>[x.clave,parseConfig(x)]));setData(c=>({...c,...masters,products,purchases:purchases.map(ops.mapPurchase),stockMovements:(stockMovements.items||stockMovements||[]).map(ops.mapStock),orders:(orders.items||orders||[]).map(ops.mapOrder),settings:{...c.settings,...settings},webContent:{banners:banners.map(b=>({id:b.id,active:b.activo,order:b.orden,title:b.titulo,subtitle:b.subtitulo,desktopImage:b.imagenDesktopUrl,mobileImage:b.imagenMobileUrl,desktopCloudflareImageId:b.imagenDesktopCloudflareId||null,mobileCloudflareImageId:b.imagenMobileCloudflareId||null,ctaLink:b.linkUrl})),brandCarousel:masters.brands.filter(x=>x.active).map((b,i)=>({...b,order:i+1,searchQuery:b.name}))}}))},[])
 const checkAdminSession=useCallback(async()=>{setAdminState('checking');try{await adminAuth.session();setAdminState('authenticated');await refreshAdmin();setAdminError('')}catch(e){if(e?.status===401||e?.status===403){setAdminState('anonymous');return}setAdminState('unavailable');setAdminError(friendly(e,'No se pudo validar la sesión.'))}},[refreshAdmin])
 useEffect(()=>{loadPublicCatalog();const path=window.location.pathname;const isAdmin=path.startsWith('/admin')||path===ADMIN_LOGIN_PATH;if(isAdmin)checkAdminSession();else setAdminState('anonymous')},[loadPublicCatalog,checkAdminSession])
 const loginAdmin=useCallback(async code=>{await adminAuth.login(code);setAdminState('authenticated');await refreshAdmin()},[refreshAdmin]);const logoutAdmin=useCallback(async()=>{try{await adminAuth.logout()}finally{setAdminState('anonymous')}},[])
 const refresh=async()=>{await refreshAdmin();await loadPublicCatalog()}
 const api=useMemo(()=>({data,loading:catalogState==='loading',error:catalogError,catalogState,catalogError,adminState,adminError,cart,cartCount:cart.reduce((s,x)=>s+x.quantity,0),loginAdmin,logoutAdmin,checkAdminSession,refreshCatalog:adminState==='authenticated'?refreshAdmin:loadPublicCatalog,retryPublicCatalog:loadPublicCatalog,scanProduct:apiCatalogRepository.scan,
 addToCart(productId,quantity=1,variantId=null){const p=data.products.find(x=>x.id===productId&&x.active);const v=p?.variants?.find(x=>x.id===(variantId||p.variants.find(y=>y.isDefault)?.id));const stock=Number(v?.availableStock??p?.stock??0);if(!p||!v||stock<=0)return;setCart(c=>{const f=c.find(x=>x.productId===productId&&x.variantId===v.id);const q=Math.min(stock,(f?.quantity||0)+Number(quantity||1));return f?c.map(x=>x===f?{...x,quantity:q}:x):[...c,{productId,variantId:v.id,quantity:q}]})},updateCartQuantity(productId,quantity,variantId=null){const p=data.products.find(x=>x.id===productId);const v=p?.variants?.find(x=>x.id===variantId)||p?.variants?.find(x=>x.isDefault);const q=Math.max(0,Math.min(Number(v?.availableStock??0),Number(quantity)||0));setCart(c=>q?c.map(x=>x.productId===productId&&(!variantId||x.variantId===variantId)?{...x,quantity:q}:x):c.filter(x=>!(x.productId===productId&&(!variantId||x.variantId===variantId))))},removeFromCart(id,variantId=null){setCart(c=>c.filter(x=>!(x.productId===id&&(!variantId||x.variantId===variantId))))},clearCart(){setCart([])},
 async saveProduct(x){
  const r=await apiCatalogRepository.saveProduct(x);
  setData(c=>({...c,products:[...c.products.filter(p=>p.id!==r.id),r].sort((a,b)=>a.name.localeCompare(b.name,'es'))}));
  try{await refresh()}catch(err){console.warn('Producto guardado; no se pudo refrescar toda la aplicación.',err)}
  return r
},async toggleProduct(id){const p=data.products.find(x=>x.id===id);await apiCatalogRepository.setProductActive(id,!p.active);await refresh()},
 async saveBrand(x){await ops.saveBrand(x);await refreshAdmin()},async toggleBrand(id){const x=data.brands.find(b=>b.id===id);await ops.brandState(id,!x.active);await refreshAdmin()},async saveProductCategory(x){await ops.saveCategory({id:x.id||null,name:x.name,parentId:null,order:x.order||0,active:x.active!==false});await refreshAdmin()},async toggleProductCategory(id){const x=data.allCategories.find(c=>c.id===id);await ops.categoryState(id,!x.active);await refreshAdmin()},async saveSubcategory(parentId,x){await ops.saveCategory({id:x.id||null,name:x.name,parentId,order:x.order||0,active:x.active!==false});await refreshAdmin()},async toggleSubcategory(_parentId,id){const x=data.allCategories.find(c=>c.id===id);await ops.categoryState(id,!x.active);await refreshAdmin()},
 async saveSupplier(x){await ops.saveSupplier(x);await refreshAdmin()},async toggleSupplier(id){const x=data.suppliers.find(s=>s.id===id);await ops.supplierState(id,!x.active);await refreshAdmin()},async adjustStock(productId,newStock,note){const p=data.products.find(x=>x.id===productId);const v=p?.variants?.find(x=>x.isDefault)||p?.variants?.[0];if(!v)throw new Error('El producto no tiene una variante vendible.');await ops.adjustStock(v.id,newStock,note);await refreshAdmin()},
 async registerPurchase(x){const gross=x.items.reduce((s,i)=>s+i.quantity*i.unitCost,0);const payload={...x,grossTotal:gross,discountAmount:discountAmount({...x,grossTotal:gross})};const r=await ops.createPurchase(payload);await refreshAdmin();return{...r,number:r.numero||r.number}},async confirmSale(x){try{const gross=x.items.reduce((s,i)=>s+i.quantity*i.unitPrice,0);const r=await ops.createSale({...x,grossTotal:gross,discountAmount:discountAmount({...x,grossTotal:gross})},data.products);await refreshAdmin();const sale=ops.mapSale(await ops.saleById(r.id));return{ok:true,sale}}catch(e){return{ok:false,error:friendly(e,'No se pudo registrar la venta.')}}},
 async registerCashMovement(x){const out=['owner_withdrawal','manual_expense'].includes(x.category);const description=[x.concept,x.notes].filter(Boolean).join(' · ');await ops.createCash({...x,concept:description,direction:out?'out':'in'});await refreshAdmin();return{ok:true}},
 async createOrder(x){const r=await ops.createOrder({...x,products:data.products});setCart([]);return{...r,trackingCode:r.trackingCode}},async advanceOrder(id){try{await ops.advanceOrder(id);await refreshAdmin();return{ok:true}}catch(e){return{ok:false,error:friendly(e,'No se pudo avanzar el pedido.')}}},async cancelOrder(id){try{await ops.cancelOrder(id);await refreshAdmin();return{ok:true}}catch(e){return{ok:false,error:friendly(e,'No se pudo cancelar el pedido.')}}},async confirmOrderPayment(id){try{await ops.confirmPayment(id);await refreshAdmin();return{ok:true}}catch(e){return{ok:false,error:friendly(e,'No se pudo confirmar el pago.')}}},trackOrder:ops.track,
 async saveSettings(settings){const items=Object.entries(settings).filter(([,v])=>['string','number','boolean'].includes(typeof v)).map(([clave,v])=>({clave,valor:String(v),tipo:typeof v,publica:true}));await ops.saveConfig(items);setData(c=>({...c,settings}))},async saveWebBanner(x){await ops.saveBanner({id:x.id||null,titulo:x.title||'',subtitulo:x.subtitle||null,imagenDesktopCloudflareId:x.desktopCloudflareImageId||null,imagenMobileCloudflareId:x.mobileCloudflareImageId||null,quitarImagenMobile:x.removeMobileImage===true,linkUrl:x.ctaLink||null,orden:Number(x.order||0),activo:x.active!==false});await refreshAdmin()},async deleteWebBanner(id){await ops.deleteBanner(id);await refreshAdmin()},async saveBrandCarouselItem(x){const existing=data.brands.find(b=>b.id===x.id)||data.brands.find(b=>b.name===x.name);await ops.saveBrand({...existing,...x,id:existing?.id||null});await refreshAdmin()},async deleteBrandCarouselItem(id){await ops.brandState(id,false);await refreshAdmin()}
 }),[data,catalogState,catalogError,adminState,adminError,cart,loginAdmin,logoutAdmin,checkAdminSession,refreshAdmin,loadPublicCatalog])
 return <AppDataContext.Provider value={api}>{children}</AppDataContext.Provider>
}
export const useAppData=()=>useContext(AppDataContext)
