export const siteConfig = {
  technicalName: 'RCRepuestosYAccesorios',
  displayName: 'RC Repuestos y Accesorios',
  tagline: 'Repuestos · Accesorios · Atención personalizada',
  heroTitle: 'Todo para tu moto. En un solo lugar.',
  heroSubtitle: 'Repuestos y accesorios con catálogo online y atención personalizada.',
  phone: import.meta.env.VITE_RC_PHONE || '',
  whatsapp: import.meta.env.VITE_RC_WHATSAPP || '',
  email: import.meta.env.VITE_RC_EMAIL || '',
  address: import.meta.env.VITE_RC_ADDRESS || '',
  instagram: import.meta.env.VITE_RC_INSTAGRAM || '',
  domain: import.meta.env.VITE_RC_DOMAIN || '',
  businessHours: import.meta.env.VITE_RC_BUSINESS_HOURS || '',
  storeEnabled: true,
  showPrices: true,
  accent: '#ef1f26',
  ordersEnabled: false,
  storePickupMessage: 'La disponibilidad y compatibilidad se confirman antes de cerrar la operación.',
  currency: 'ARS',
  lowStockThreshold: 4,
  priceRoundingStep: 500,
  priceRoundingMode: 'up',
  wholesaleMessage: 'Consultanos por precio mayorista indicando producto y cantidad.',
  cashTransferDiscountPercent: 0,
}
