import { useMemo,useState } from 'react'
import { Edit3,Eye,EyeOff,Plus,Search } from 'lucide-react'
import { useAppData } from '../../context/AppDataContext'
import ProductEditor from '../../components/ProductEditor'
import { money } from '../../utils/commerce'

export default function AdminProductsPage(){
 const {data,loading,saveProduct,toggleProduct}=useAppData(); const [query,setQuery]=useState(''); const [editing,setEditing]=useState(undefined)
 const filtered=useMemo(()=>data?.products.filter(x=>!query.trim()||`${x.name} ${x.brand} ${x.sku}`.toLowerCase().includes(query.toLowerCase()))||[],[data,query]); if(loading)return <div className="screen-loader">Cargando…</div>
 const save=async item=>{await saveProduct(item);setEditing(undefined)}
 return <><div className="admin-page-header"><div><span className="section-kicker">Catálogo comercial</span><h1>Productos</h1><p>Definí producto, costo, política de precio y stock mínimo. Las existencias reales se mueven desde compras, ventas o ajustes.</p></div><button className="btn btn-primary" onClick={()=>setEditing(null)}><Plus size={17}/> Nuevo producto</button></div><label className="search-box admin-search"><Search size={18}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar producto, marca o SKU…"/></label><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Producto</th><th>Costo</th><th>Precio venta</th><th>Stock</th><th>Precio</th><th>Estado</th><th>Acciones</th></tr></thead><tbody>{filtered.map(x=><tr key={x.id}><td data-label="Producto"><div className="product-cell"><img src={x.image} alt=""/><div><strong>{x.name}</strong><small>{x.sku} · {x.brand}</small></div></div></td><td data-label="Costo">{money(x.costPrice)}</td><td data-label="Precio venta"><strong>{money(x.price)}</strong></td><td data-label="Stock"><span className={x.stock<=x.minStock?'stock-low':''}>{x.stock}</span><small className="table-sub">mín. {x.minStock}</small></td><td data-label="Precio"><span className={`status ${x.autoPrice?'confirmed':'inactive'}`}>{x.autoPrice?'Automático':'Manual'}</span></td><td data-label="Estado"><span className={`status ${x.active?'active':'inactive'}`}>{x.active?'Activo':'Inactivo'}</span></td><td data-label="Acciones"><div className="table-actions"><button onClick={()=>setEditing(x)}><Edit3 size={16}/></button><button onClick={()=>toggleProduct(x.id)}>{x.active?<EyeOff size={16}/>:<Eye size={16}/>}</button></div></td></tr>)}</tbody></table></div>{editing!==undefined&&<ProductEditor product={editing} data={data} onClose={()=>setEditing(undefined)} onSave={save}/>}</>
}
