import { useMemo, useState } from 'react'
import { Image, Plus, Save, Trash2, Upload, BadgeCheck } from 'lucide-react'
import { useAppData } from '../../context/AppDataContext'

const emptyBanner={id:null,active:true,order:1,eyebrow:'',title:'',subtitle:'',ctaText:'Ver productos',ctaLink:'/catalogo',desktopImage:'',mobileImage:'',overlay:'left'}
const emptyBrand={id:null,name:'',logoUrl:'',searchQuery:'',order:1,active:true}

const fileToDataUrl=file=>new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(file)})

export default function AdminWebContentPage(){
 const {data,loading,saveWebBanner,deleteWebBanner,saveBrandCarouselItem,deleteBrandCarouselItem}=useAppData()
 const [banner,setBanner]=useState(emptyBanner); const [brand,setBrand]=useState(emptyBrand); const [message,setMessage]=useState('')
 const banners=useMemo(()=>[...(data?.webContent?.banners||[])].sort((a,b)=>(a.order||0)-(b.order||0)),[data]); const brands=useMemo(()=>[...(data?.webContent?.brandCarousel||[])].sort((a,b)=>(a.order||0)-(b.order||0)),[data])
 if(loading)return <div className="screen-loader">Cargando contenido…</div>
 const saveBanner=async e=>{e.preventDefault();if(!banner.title||!banner.desktopImage){setMessage('El banner necesita título e imagen de escritorio.');return}await saveWebBanner(banner);setBanner({...emptyBanner,order:banners.length+2});setMessage('Banner guardado. El carrusel público se actualizó.')}
 const saveBrand=async e=>{e.preventDefault();if(!brand.name||!brand.logoUrl){setMessage('La marca necesita nombre y logo.');return}await saveBrandCarouselItem({...brand,searchQuery:brand.searchQuery||brand.name});setBrand({...emptyBrand,order:brands.length+2});setMessage('Marca guardada en la pasarela.')}
 const upload=async(e,field,setter,state)=>{const file=e.target.files?.[0];if(!file)return;const url=await fileToDataUrl(file);setter({...state,[field]:url})}
 return <><div className="admin-page-header"><div><span className="section-kicker">Sitio público</span><h1>Banners y marcas</h1><p>Para la presentación podés pegar una URL o cargar una imagen local. En producción las imágenes se subirán a storage/CDN y la base de datos guardará únicamente su URL y metadatos.</p></div></div>{message&&<div className="notice-success">{message}</div>}
 <div className="content-admin-grid"><section className="admin-panel"><div className="panel-title-row"><div><h2>Carrusel principal</h2><p>Desktop recomendado 1920×720 o relación 8:3. Mobile recomendado 1080×1350 (4:5).</p></div><Image/></div><div className="content-item-list">{banners.map(x=><article key={x.id} className="content-preview-row"><img src={x.desktopImage} alt=""/><div><strong>{x.order}. {x.title}</strong><span>{x.active?'Visible':'Oculto'} · {x.eyebrow}</span></div><button className="btn btn-secondary" onClick={()=>setBanner({...x})}>Editar</button><button className="danger-icon" onClick={()=>deleteWebBanner(x.id)}><Trash2 size={16}/></button></article>)}</div>
 <form className="content-editor" onSubmit={saveBanner}><h3>{banner.id?'Editar banner':'Nuevo banner'}</h3><div className="form-grid"><label><span>Orden</span><input type="number" min="1" value={banner.order} onChange={e=>setBanner({...banner,order:e.target.value})}/></label><label className="check-label"><input type="checkbox" checked={banner.active} onChange={e=>setBanner({...banner,active:e.target.checked})}/><span>Visible</span></label></div><label><span>Etiqueta</span><input value={banner.eyebrow} onChange={e=>setBanner({...banner,eyebrow:e.target.value})} placeholder="TU MOTO, NUESTRA PASIÓN"/></label><label><span>Título</span><input value={banner.title} onChange={e=>setBanner({...banner,title:e.target.value})}/></label><label><span>Descripción</span><textarea value={banner.subtitle} onChange={e=>setBanner({...banner,subtitle:e.target.value})}/></label><div className="form-grid"><label><span>Texto botón</span><input value={banner.ctaText} onChange={e=>setBanner({...banner,ctaText:e.target.value})}/></label><label><span>Destino</span><input value={banner.ctaLink} onChange={e=>setBanner({...banner,ctaLink:e.target.value})} placeholder="/catalogo o whatsapp"/></label></div><label><span>Imagen desktop (URL)</span><input value={banner.desktopImage} onChange={e=>setBanner({...banner,desktopImage:e.target.value})}/><span className="file-inline"><Upload size={15}/> o cargar archivo <input type="file" accept="image/*" onChange={e=>upload(e,'desktopImage',setBanner,banner)}/></span></label><label><span>Imagen mobile (URL)</span><input value={banner.mobileImage} onChange={e=>setBanner({...banner,mobileImage:e.target.value})}/><span className="file-inline"><Upload size={15}/> o cargar archivo <input type="file" accept="image/*" onChange={e=>upload(e,'mobileImage',setBanner,banner)}/></span></label>{banner.desktopImage&&<div className="banner-admin-preview"><img src={banner.desktopImage} alt="Preview desktop"/></div>}<div className="editor-actions"><button className="btn btn-primary"><Save size={16}/> Guardar banner</button><button className="btn btn-secondary" type="button" onClick={()=>setBanner({...emptyBanner,order:banners.length+1})}><Plus size={16}/> Nuevo</button></div></form></section>

 <section className="admin-panel"><div className="panel-title-row"><div><h2>Pasarela de marcas</h2><p>Los logos se desplazan automáticamente y cada uno lleva al catálogo filtrado.</p></div><BadgeCheck/></div><div className="content-item-list brand-admin-list">{brands.map(x=><article key={x.id} className="content-preview-row"><div className="brand-mini"><img src={x.logoUrl} alt={x.name}/></div><div><strong>{x.order}. {x.name}</strong><span>{x.active?'Visible':'Oculto'} · busca “{x.searchQuery}”</span></div><button className="btn btn-secondary" onClick={()=>setBrand({...x})}>Editar</button><button className="danger-icon" onClick={()=>deleteBrandCarouselItem(x.id)}><Trash2 size={16}/></button></article>)}</div><form className="content-editor" onSubmit={saveBrand}><h3>{brand.id?'Editar marca':'Nueva marca'}</h3><div className="form-grid"><label><span>Nombre</span><input value={brand.name} onChange={e=>setBrand({...brand,name:e.target.value})}/></label><label><span>Orden</span><input type="number" min="1" value={brand.order} onChange={e=>setBrand({...brand,order:e.target.value})}/></label></div><label><span>Texto para búsqueda</span><input value={brand.searchQuery} onChange={e=>setBrand({...brand,searchQuery:e.target.value})} placeholder="Ej: NGK"/></label><label><span>Logo (URL o /brands/logo.svg)</span><input value={brand.logoUrl} onChange={e=>setBrand({...brand,logoUrl:e.target.value})}/><span className="file-inline"><Upload size={15}/> o cargar archivo <input type="file" accept="image/*" onChange={e=>upload(e,'logoUrl',setBrand,brand)}/></span></label><label className="check-label"><input type="checkbox" checked={brand.active} onChange={e=>setBrand({...brand,active:e.target.checked})}/><span>Visible</span></label>{brand.logoUrl&&<div className="brand-large-preview"><img src={brand.logoUrl} alt="Preview logo"/></div>}<div className="editor-actions"><button className="btn btn-primary"><Save size={16}/> Guardar marca</button><button className="btn btn-secondary" type="button" onClick={()=>setBrand({...emptyBrand,order:brands.length+1})}><Plus size={16}/> Nueva</button></div></form></section></div>
 <div className="admin-panel storage-note"><strong>Arquitectura recomendada para producción</strong><p><b>Base de datos:</b> título, orden, activo, CTA, URL desktop y URL mobile. <b>Storage/CDN:</b> archivos WebP/AVIF optimizados. Así el contenido puede cambiarse sin recompilar el frontend, pero la aplicación sigue siendo rápida y escalable.</p></div></>
}
