import { useEffect,useState } from 'react'
import { ArrowRight, Plus, ReceiptText, Search } from 'lucide-react'
import { Link } from 'react-router-dom'
import { operationsRepository as ops } from '../../repositories/operationsRepository'
import { dateTime, money } from '../../utils/commerce'
const PAGE_SIZE=5
export default function AdminSalesPage(){
 const[page,setPage]=useState(1),[query,setQuery]=useState(''),[source,setSource]=useState('all'),[result,setResult]=useState({items:[],page:1,total:0,totalPages:1,summary:{}}),[loading,setLoading]=useState(true),[error,setError]=useState('')
 useEffect(()=>{const t=setTimeout(async()=>{setLoading(true);setError('');try{setResult(await ops.salesHistory(page,PAGE_SIZE,query,source))}catch(e){setError(e.message||'No se pudo cargar el historial de ventas.')}finally{setLoading(false)}},250);return()=>clearTimeout(t)},[page,query,source])
 const changeQuery=v=>{setQuery(v);setPage(1)},changeSource=v=>{setSource(v);setPage(1)}
 return <><div className="admin-page-header compact-page-header"><div><span className="section-kicker">Comercial</span><h1>Historial de ventas</h1><p>Ventas confirmadas, ordenadas desde la más reciente. La venta presencial se registra desde Punto de Venta.</p></div><Link className="btn btn-primary" to="/admin/pos"><Plus size={17}/> Nueva venta</Link></div>
 <div className="summary-strip"><div><span>Ventas encontradas</span><strong>{result.summary?.count??result.total??0}</strong></div><div><span>Facturación</span><strong>{money(result.summary?.billed||0)}</strong></div><div><span>Margen bruto</span><strong>{money(result.summary?.grossProfit||0)}</strong></div></div>
 <section className="admin-panel sales-list-panel"><div className="list-toolbar"><label className="search-box"><Search size={18}/><input value={query} onChange={e=>changeQuery(e.target.value)} placeholder="Buscar por número, cliente o teléfono…"/></label><select value={source} onChange={e=>changeSource(e.target.value)}><option value="all">Todos los canales</option><option value="pos">Venta presencial</option><option value="whatsapp_order">Pedido web / WhatsApp</option></select></div>
 {error&&<div className="notice-error">{error}</div>}<div className="admin-table-wrap sales-table-wrap"><table className="admin-table sales-table"><thead><tr><th>Venta</th><th>Fecha</th><th>Cliente</th><th>Canal</th><th>Pago</th><th>Descuento</th><th>Total</th><th>Margen bruto</th><th></th></tr></thead><tbody>{!loading&&result.items.map(raw=>{const s=ops.mapSale(raw);return <tr key={s.id}><td><strong>{s.number}</strong></td><td>{dateTime(s.createdAt)}</td><td>{s.customerName||'Consumidor final'}</td><td><span className="status-pill neutral">{s.source==='whatsapp_order'?'Pedido web':'Presencial'}</span></td><td>{s.paymentMethod}</td><td>{s.discountAmount?money(s.discountAmount):'—'}</td><td><strong>{money(s.total)}</strong></td><td><span className="profit-text">{money(s.grossProfit)}</span></td><td><Link className="table-link" to={`/admin/ventas/${s.id}`}>Ver detalle <ArrowRight size={14}/></Link></td></tr>})}{loading&&<tr><td colSpan="9"><div className="empty-agenda">Cargando ventas…</div></td></tr>}{!loading&&!result.items.length&&<tr><td colSpan="9"><div className="empty-agenda"><ReceiptText size={22}/> No hay ventas que coincidan con los filtros.</div></td></tr>}</tbody></table></div>
 <div className="inventory-pagination"><button disabled={page<=1||loading} onClick={()=>setPage(v=>v-1)}>Anterior</button><span>Página <b>{result.page||page}</b> de <b>{Math.max(1,result.totalPages||1)}</b> · {result.total||0} registros</span><button disabled={page>=Math.max(1,result.totalPages||1)||loading} onClick={()=>setPage(v=>v+1)}>Siguiente</button></div></section></>
}