import { useEffect,useState } from 'react'
import { ArrowDownCircle, ArrowUpCircle, Banknote, CircleDollarSign, Plus, Search, WalletCards, X } from 'lucide-react'
import { useAppData } from '../../context/AppDataContext'
import { operationsRepository as ops } from '../../repositories/operationsRepository'
import { dateTime, money } from '../../utils/commerce'
import { cashCategoryLabel } from '../../utils/cash'
const PAGE_SIZE=5, paymentOptions=['Efectivo','Transferencia','Mercado Pago','Tarjeta / banco','Otro']
export default function AdminCashPage(){const{registerCashMovement}=useAppData();const[period,setPeriod]=useState('30'),[query,setQuery]=useState(''),[category,setCategory]=useState('all'),[page,setPage]=useState(1),[result,setResult]=useState({items:[],summary:{},byMethod:[],totalPages:1,total:0}),[loading,setLoading]=useState(true),[modal,setModal]=useState(false),[movementType,setMovementType]=useState('capital_deposit'),[form,setForm]=useState({amount:'',paymentMethod:'Efectivo',concept:'',notes:''}),[message,setMessage]=useState(''),[error,setError]=useState('')
 const load=async()=>{setLoading(true);setError('');try{setResult(await ops.cashHistory(page,PAGE_SIZE,period,query,category))}catch(e){setError(e.message||'No se pudo cargar Caja.')}finally{setLoading(false)}}
 useEffect(()=>{const t=setTimeout(load,250);return()=>clearTimeout(t)},[page,period,query,category])
 const reset=(setter,v)=>{setter(v);setPage(1)},open=()=>{setModal(true);setMovementType('capital_deposit');setMessage('');setForm({amount:'',paymentMethod:'Efectivo',concept:'',notes:''})}
 const submit=async e=>{e.preventDefault();setError('');const amount=Number(form.amount)||0;if(amount<=0){setError('Ingresá un importe mayor a cero.');return}const labels={capital_deposit:'Ingreso de fondos',owner_withdrawal:'Retiro de fondos',manual_income:'Otro ingreso',manual_expense:'Otro egreso'};if(['manual_income','manual_expense'].includes(movementType)&&!form.concept.trim()){setError('Indicá el concepto del movimiento.');return}try{await registerCashMovement({category:movementType,amount,paymentMethod:form.paymentMethod,concept:form.concept.trim()||labels[movementType],notes:form.notes.trim()});setModal(false);setMessage('Movimiento registrado correctamente en Caja.');await load()}catch(e){setError(e.message||'No se pudo registrar el movimiento.')}}
 const s=result.summary||{};return <><div className="admin-page-header compact-page-header"><div><span className="section-kicker">Tesorería</span><h1>Caja general</h1><p>Trazabilidad paginada de ventas, compras, ingresos y retiros.</p></div><button className="btn btn-primary" onClick={open}><Plus size={17}/> Movimiento manual</button></div>{message&&<div className="notice-success">{message}</div>}{error&&<div className="notice-error">{error}</div>}
 <section className="cash-balance-hero admin-panel"><div><span>Saldo actual de caja</span><strong>{money(s.balance||0)}</strong><small>Calculado sobre todos los movimientos registrados.</small></div><WalletCards size={34}/></section>
 <div className="cash-kpi-grid"><article><ArrowUpCircle/><div><span>Ingresos operativos · período</span><strong>{money(s.operationalIncome||0)}</strong><small>Ventas + otros ingresos</small></div></article><article><ArrowDownCircle/><div><span>Egresos operativos · período</span><strong>{money(s.operationalExpense||0)}</strong><small>Compras + otros egresos</small></div></article><article><CircleDollarSign/><div><span>Resultado operativo</span><strong className={(s.operatingCashResult||0)>=0?'profit-text':'danger-text'}>{money(s.operatingCashResult||0)}</strong><small>No equivale a utilidad contable.</small></div></article><article><Banknote/><div><span>Movimientos de capital</span><strong>{money((s.deposits||0)-(s.withdrawals||0))}</strong><small>Ingresos de fondos − retiros</small></div></article></div>
 <section className="admin-panel cash-account-panel"><div className="panel-title-row"><div><h2>Saldo por medio / cuenta</h2><p>Distribución histórica calculada en el servidor.</p></div></div><div className="cash-method-grid">{(result.byMethod||[]).map(x=><div key={x.method}><span>{['','Efectivo','Transferencia','Mercado Pago','Tarjeta / banco','Otro'][x.method]||'Otro'}</span><strong>{money(x.value)}</strong></div>)}</div></section>
 <section className="admin-panel"><div className="cash-toolbar"><div><h2>Movimientos</h2><p>Se muestran {PAGE_SIZE} movimientos por página, siempre con los más recientes primero.</p></div><div className="cash-periods">{[['7','7 días'],['30','30 días'],['90','90 días'],['all','Todo']].map(([v,l])=><button key={v} className={period===v?'active':''} onClick={()=>reset(setPeriod,v)}>{l}</button>)}</div></div><div className="list-toolbar cash-filter-toolbar"><label className="search-box"><Search size={18}/><input value={query} onChange={e=>reset(setQuery,e.target.value)} placeholder="Buscar concepto o referencia…"/></label><select value={category} onChange={e=>reset(setCategory,e.target.value)}><option value="all">Todos los movimientos</option><option value="product_sale">Ventas</option><option value="purchase">Compras</option><option value="capital_deposit">Ingresos de fondos</option><option value="owner_withdrawal">Retiros</option><option value="manual_income">Otros ingresos</option><option value="manual_expense">Otros egresos</option></select></div>
 <div className="cash-movement-list">{!loading&&(result.items||[]).map(raw=>{const m=ops.mapCash(raw);return <article key={m.id}><div className={`cash-direction ${m.direction}`}>{m.direction==='in'?<ArrowUpCircle/>:<ArrowDownCircle/>}</div><div className="cash-movement-main"><div><strong>{m.concept}</strong><span className="status-pill neutral">{cashCategoryLabel(m.category)}</span></div><small>{dateTime(m.createdAt)} · {m.reference||'Sin referencia'} · {m.paymentMethod}</small></div><strong className={m.direction==='in'?'cash-in':'cash-out'}>{m.direction==='in'?'+':'−'} {money(m.amount)}</strong></article>})}{loading&&<div className="empty-agenda">Cargando movimientos…</div>}{!loading&&!result.items?.length&&<div className="empty-agenda">No hay movimientos para los filtros seleccionados.</div>}</div><div className="inventory-pagination"><button disabled={page<=1||loading} onClick={()=>setPage(v=>v-1)}>Anterior</button><span>Página <b>{result.page||page}</b> de <b>{Math.max(1,result.totalPages||1)}</b> · {result.total||0} registros</span><button disabled={page>=Math.max(1,result.totalPages||1)||loading} onClick={()=>setPage(v=>v+1)}>Siguiente</button></div></section>
 {modal&&<div className="modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&setModal(false)}><div className="modal cash-modal admin-form-modal"><button className="modal-close" type="button" aria-label="Cerrar" onClick={()=>setModal(false)}><X size={18}/></button><div className="admin-modal-heading"><span className="section-kicker">Caja general</span><h2>Registrar movimiento manual</h2><p>Registrá únicamente movimientos que no provienen de una venta o compra. El sistema determina automáticamente si es un ingreso o un egreso.</p></div><form className="admin-modal-form" onSubmit={submit}><label className="admin-field"><span>Tipo de movimiento</span><select value={movementType} onChange={e=>{setMovementType(e.target.value);setForm(f=>({...f,concept:''}))}}><option value="capital_deposit">Ingreso de fondos / capital</option><option value="owner_withdrawal">Retiro de fondos</option><option value="manual_income">Otro ingreso</option><option value="manual_expense">Otro egreso</option></select></label><div className="admin-modal-two-cols"><label className="admin-field"><span>Importe</span><input type="number" min="0.01" step="0.01" value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})} placeholder="0,00" required autoFocus/></label><label className="admin-field"><span>Medio / cuenta</span><select value={form.paymentMethod} onChange={e=>setForm({...form,paymentMethod:e.target.value})}>{paymentOptions.map(x=><option key={x}>{x}</option>)}</select></label></div>{['manual_income','manual_expense'].includes(movementType)&&<label className="admin-field"><span>Concepto</span><input value={form.concept} onChange={e=>setForm({...form,concept:e.target.value})} placeholder={movementType==='manual_income'?'Ej: reintegro o ajuste positivo':'Ej: flete o gasto eventual'} required/></label>}<label className="admin-field"><span>Observación <small>Opcional</small></span><textarea rows="3" value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})} placeholder="Detalle breve para auditoría interna"/></label><div className={`cash-manual-preview ${['owner_withdrawal','manual_expense'].includes(movementType)?'out':'in'}`}><div><strong>{['owner_withdrawal','manual_expense'].includes(movementType)?'Egreso':'Ingreso'}</strong><small>Clasificación automática</small></div><span>Se registrará en {form.paymentMethod||'la cuenta seleccionada'}.</span></div><div className="admin-modal-actions"><button className="btn btn-secondary" type="button" onClick={()=>setModal(false)}>Cancelar</button><button className="btn btn-primary" type="submit">Registrar movimiento</button></div></form></div></div>}</>}