import { useState } from 'react'
import { Edit3, Eye, EyeOff, Plus, X } from 'lucide-react'
import { useAppData } from '../../context/AppDataContext'

function TextEditor({ title, initialName='', onCancel, onSave }) {
  const [name, setName] = useState(initialName)
  return <div className="inline-editor"><strong>{title}</strong><input autoFocus value={name} onChange={e=>setName(e.target.value)} placeholder="Nombre"/><div><button className="btn btn-secondary" onClick={onCancel}>Cancelar</button><button className="btn btn-primary" onClick={()=>name.trim()&&onSave(name.trim())}>Guardar</button></div></div>
}

export default function AdminCatalogPage(){
  const api=useAppData(); const {data,loading}=api; const [tab,setTab]=useState('products'); const [editor,setEditor]=useState(null); const [brandForm,setBrandForm]=useState(null)
  if(loading)return <div className="screen-loader">Cargando catálogo…</div>
  const saveText=async name=>{ if(editor.type==='productCategory')await api.saveProductCategory({id:editor.item?.id||0,name,active:editor.item?.active??true,subcategories:editor.item?.subcategories||[]}); if(editor.type==='subcategory')await api.saveSubcategory(editor.categoryId,{id:editor.item?.id||0,name,active:editor.item?.active??true}); setEditor(null) }
  const openBrand=item=>setBrandForm(item?{...item}:{id:0,name:'',active:true,defaultMarkupPercent:0})
  const saveBrand=async e=>{e.preventDefault();await api.saveBrand({...brandForm,defaultMarkupPercent:Number(brandForm.defaultMarkupPercent)||0});setBrandForm(null)}
  return <>
    <div className="admin-page-header"><div><span className="section-kicker">Estructura comercial</span><h1>Marcas y categorías</h1><p>Las marcas pueden definir un porcentaje base que luego heredan los productos.</p></div></div>
    <div className="catalog-tabs"><button className={tab==='products'?'active':''} onClick={()=>setTab('products')}>Categorías</button><button className={tab==='brands'?'active':''} onClick={()=>setTab('brands')}>Marcas y porcentajes</button></div>
    {editor&&<TextEditor title={editor.title} initialName={editor.item?.name||''} onCancel={()=>setEditor(null)} onSave={saveText}/>}    
    {tab==='brands'&&<div className="catalog-panel"><div className="panel-heading"><div><h2>Marcas</h2><p>Porcentaje automático aplicado después del porcentaje del proveedor.</p></div><button className="btn btn-primary" onClick={()=>openBrand(null)}><Plus size={16}/> Nueva marca</button></div><div className="entity-list">{data.brands.map(x=><div className="entity-row" key={x.id}><div><strong>{x.name}</strong><span>Margen base: <b>{Number(x.defaultMarkupPercent||0)}%</b></span><span className={`status ${x.active?'active':'inactive'}`}>{x.active?'Activa':'Inactiva'}</span></div><div className="table-actions"><button onClick={()=>openBrand(x)}><Edit3 size={16}/></button><button onClick={()=>api.toggleBrand(x.id)}>{x.active?<EyeOff size={16}/>:<Eye size={16}/>}</button></div></div>)}</div></div>}
    {tab==='products'&&<div className="category-admin-grid"><div className="panel-heading wide-heading"><h2>Categorías y subcategorías</h2><button className="btn btn-primary" onClick={()=>setEditor({type:'productCategory',title:'Nueva categoría'})}><Plus size={16}/> Nueva categoría</button></div>{data.productCategories.map(category=><article className="category-admin-card" key={category.id}><div className="category-card-head"><div><h3>{category.name}</h3><span className={`status ${category.active?'active':'inactive'}`}>{category.active?'Activa':'Inactiva'}</span></div><div className="table-actions"><button onClick={()=>setEditor({type:'productCategory',item:category,title:'Editar categoría'})}><Edit3 size={16}/></button><button onClick={()=>api.toggleProductCategory(category.id)}>{category.active?<EyeOff size={16}/>:<Eye size={16}/>}</button></div></div><div className="subcategory-list">{category.subcategories.map(sub=><div key={sub.id}><span>{sub.name}</span><span className={`status ${sub.active?'active':'inactive'}`}>{sub.active?'Activa':'Inactiva'}</span><div className="table-actions"><button onClick={()=>setEditor({type:'subcategory',categoryId:category.id,item:sub,title:'Editar subcategoría'})}><Edit3 size={15}/></button><button onClick={()=>api.toggleSubcategory(category.id,sub.id)}>{sub.active?<EyeOff size={15}/>:<Eye size={15}/>}</button></div></div>)}</div><button className="add-subcategory" onClick={()=>setEditor({type:'subcategory',categoryId:category.id,title:`Nueva subcategoría en ${category.name}`})}><Plus size={15}/> Agregar subcategoría</button></article>)}</div>}
    {brandForm&&<div className="modal-backdrop"><div className="modal"><button className="modal-close" onClick={()=>setBrandForm(null)}><X size={20}/></button><span className="section-kicker">Marca</span><h2>{brandForm.id?'Editar marca':'Nueva marca'}</h2><form className="editor-form" onSubmit={saveBrand}><label><span>Nombre</span><input required value={brandForm.name} onChange={e=>setBrandForm({...brandForm,name:e.target.value})}/></label><label><span>Porcentaje base de la marca</span><div className="percent-input"><input type="number" step="0.01" value={brandForm.defaultMarkupPercent} onChange={e=>setBrandForm({...brandForm,defaultMarkupPercent:e.target.value})}/><span>%</span></div><small className="field-hint">Se suma de forma encadenada al porcentaje del proveedor y al del producto.</small></label><button className="btn btn-primary full-width">Guardar marca</button></form></div></div>}
  </>
}
