import { useMemo,useState } from 'react'
import { Eye,Search,ShoppingBag,Truck,Store,CreditCard,Clock3 } from 'lucide-react'
import { Link } from 'react-router-dom'
import { useAppData } from '../../context/AppDataContext'
import { money,dateTime } from '../../utils/commerce'
import { orderStatusLabel,paymentStatusLabel,paymentMethodLabel } from '../../utils/orderWorkflow'

export default function AdminOrdersPage(){
 const {data,loading}=useAppData(); const [query,setQuery]=useState(''); const [status,setStatus]=useState('all'); const [delivery,setDelivery]=useState('all')
 const orders=useMemo(()=>{if(!data)return[];return [...(data.orders||[])].sort((a,b)=>new Date(b.createdAt)-new Date(a.createdAt)).filter(o=>{const q=query.trim().toLowerCase();const hit=!q||[o.publicCode,o.trackingCode,o.customerName,o.phone,o.email].some(v=>String(v||'').toLowerCase().includes(q));return hit&&(status==='all'||o.status===status)&&(delivery==='all'||o.deliveryType===delivery)})},[data,query,status,delivery])
 if(loading)return <div className="screen-loader">Cargando pedidos…</div>
 const all=data.orders||[]; const active=all.filter(x=>!['completed','cancelled'].includes(x.status)).length; const awaiting=all.filter(x=>x.status==='awaiting_payment').length; const shipping=all.filter(x=>x.deliveryType==='shipping'&&['pending_shipment','shipped'].includes(x.status)).length; const paid=all.filter(x=>x.paymentStatus==='approved').length
 return <div className="orders-page-v12"><div className="admin-page-header"><div><span className="section-kicker">Operación comercial</span><h1>Pedidos</h1><p>Seguimiento operativo de pedidos, acreditaciones, ventas y entregas de RC Repuestos y Accesorios.</p></div></div>
 <div className="order-admin-stats order-kpis-v12"><article><Clock3/><div><strong>{active}</strong><span>En proceso</span></div></article><article><CreditCard/><div><strong>{awaiting}</strong><span>Esperando pago</span></div></article><article><Truck/><div><strong>{shipping}</strong><span>Envíos activos</span></div></article><article><ShoppingBag/><div><strong>{paid}</strong><span>Pagos acreditados</span></div></article></div>
 <div className="admin-panel orders-toolbar-v12"><div className="order-search-v12"><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar pedido, seguimiento, cliente o teléfono…"/></div><select value={status} onChange={e=>setStatus(e.target.value)}><option value="all">Todos los estados</option>{Object.entries(orderStatusLabel).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select><select value={delivery} onChange={e=>setDelivery(e.target.value)}><option value="all">Todas las entregas</option><option value="pickup">Retiro en sucursal</option><option value="shipping">Envío a domicilio</option></select></div>
 <div className="admin-panel orders-table-panel"><div className="orders-table-wrap"><table className="orders-table-v12"><thead><tr><th>Pedido</th><th>Cliente</th><th>Entrega</th><th>Pago</th><th>Estado pago</th><th>Estado pedido</th><th>Total</th><th></th></tr></thead><tbody>{orders.map(o=><tr key={o.id}><td><strong>{o.publicCode}</strong><small>{dateTime(o.createdAt)}</small></td><td><strong>{o.customerName||'Sin nombre'}</strong><small>{o.phone||'Sin teléfono'}</small></td><td><span className="table-icon-label">{o.deliveryType==='shipping'?<Truck size={15}/>:<Store size={15}/>} {o.deliveryType==='shipping'?'Envío':'Retiro'}</span></td><td>{paymentMethodLabel[o.paymentMethod]||o.paymentMethod||'—'}</td><td><span className={`order-badge payment-${o.paymentStatus||'pending'}`}>{paymentStatusLabel[o.paymentStatus]||o.paymentStatus||'Pendiente'}</span></td><td><span className={`order-badge order-${o.status}`}>{orderStatusLabel[o.status]||o.status}</span></td><td><strong>{money(o.total)}</strong></td><td><Link className="icon-button table-view-btn" to={`/admin/pedidos/${o.id}`} title="Ver detalle"><Eye size={17}/></Link></td></tr>)}</tbody></table>{!orders.length&&<div className="orders-empty-v12">No encontramos pedidos con estos filtros.</div>}</div></div></div>
}
