import { useMemo,useState } from 'react'
import { Edit3,Eye,EyeOff,Plus,Search } from 'lucide-react'
import { useAppData } from '../../context/AppDataContext'
import ProductEditor from '../../components/ProductEditor'
import { money } from '../../utils/commerce'
const principal=x=>(x.variants||[]).find(v=>v.active!==false&&v.isDefault)||(x.variants||[]).find(v=>v.active!==false)||{}

export default function AdminProductsPage(){
 const {data,loading,saveProduct,toggleProduct}=useAppData(); const [query,setQuery]=useState('')
 const [page,setPage]=useState(1)
 const pageSize=5; const [editing,setEditing]=useState(undefined)
 const filtered=useMemo(()=>data?.products.filter(x=>!query.trim()||`${x.name} ${x.brand} ${x.sku}`.toLowerCase().includes(query.toLowerCase()))||[],[data,query]); if(loading)return <div className="screen-loader">Cargando…</div>
 const save=async item=>{await saveProduct(item);setEditing(undefined)}
 const totalPages=Math.max(1,Math.ceil(filtered.length/pageSize)); const visible=filtered.slice((page-1)*pageSize,page*pageSize); if(page>totalPages)setTimeout(()=>setPage(totalPages),0)
 return <><div className="admin-page-header"><div><span className="section-kicker">Catálogo comercial</span><h1>Productos</h1><p>Definí producto, costo, política de precio y stock mínimo. Las existencias reales se mueven desde compras, ventas o ajustes.</p></div><button className="btn btn-primary" onClick={()=>setEditing(null)}><Plus size={17}/> Nuevo producto</button></div><label className="search-box admin-search"><Search size={18}/><input value={query} onChange={e=>{setQuery(e.target.value);setPage(1)}} placeholder="Buscar producto, marca o SKU…"/></label><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Producto</th><th>Costo</th><th>Precio venta</th><th>Stock</th><th>Precio</th><th>Estado</th><th>Acciones</th></tr></thead><tbody>{visible.map(x=><tr key={x.id}><td data-label="Producto"><div className="product-cell"><img src={principal(x).image||x.image} alt=""/><div><strong>{x.name}</strong><small>{principal(x).sku||'Sin SKU'} · {x.brand||'Sin marca'}{(x.variants||[]).filter(v=>v.active!==false).length>1?` · ${(x.variants||[]).filter(v=>v.active!==false).length} variantes`:''}</small></div></div></td><td data-label="Costo">{money(principal(x).costPrice||0)}</td><td data-label="Precio venta"><strong>{money(principal(x).price||0)}</strong></td><td data-label="Stock"><span className={x.stock<=x.minStock?'stock-low':''}>{x.stock}</span><small className="table-sub">mín. ref. {principal(x).minStock||0}</small></td><td data-label="Precio"><span className={`status ${x.autoPrice?'confirmed':'inactive'}`}>{x.autoPrice?'Automático':'Manual'}</span></td><td data-label="Estado"><span className={`status ${x.active?'active':'inactive'}`}>{x.active?'Activo':'Inactivo'}</span>{x.featured&&<span className="status confirmed">Destacado</span>}{x.newArrival&&<span className="status confirmed">Novedad</span>}{x.offerActive&&<span className="status confirmed">Oferta</span>}</td><td data-label="Acciones"><div className="table-actions"><button onClick={()=>setEditing(x)}><Edit3 size={16}/></button><button onClick={()=>toggleProduct(x.id)}>{x.active?<EyeOff size={16}/>:<Eye size={16}/>}</button></div></td></tr>)}</tbody></table></div><div className="inventory-pagination"><button disabled={page<=1} onClick={()=>setPage(v=>v-1)}>Anterior</button><span>Página <b>{page}</b> de <b>{totalPages}</b> · {filtered.length} productos</span><button disabled={page>=totalPages} onClick={()=>setPage(v=>v+1)}>Siguiente</button></div>{editing!==undefined&&<ProductEditor product={editing} data={data} onClose={()=>setEditing(undefined)} onSave={save}/>}</>
}
