import {useCallback,useEffect,useState} from 'react'
import {ChevronLeft,ChevronRight,Clock3,Search,SlidersHorizontal,TrendingDown,TrendingUp} from 'lucide-react'
import {dateTime,movementLabel,money} from '../../utils/commerce'
import {operationsRepository as ops} from '../../repositories/operationsRepository'
const SIZE=5
function Pager({page,total,onPage,loading}){const nums=Array.from({length:total},(_,i)=>i+1).filter(n=>n===1||n===total||Math.abs(n-page)<=1);return <div className="inventory-pagination"><button disabled={page<=1||loading} onClick={()=>onPage(page-1)}><ChevronLeft size={15}/>Anterior</button><div>{nums.map((n,i)=><span key={n}>{i>0&&n-nums[i-1]>1&&<i>…</i>}<button className={n===page?'active':''} onClick={()=>onPage(n)}>{n}</button></span>)}</div><button disabled={page>=total||loading} onClick={()=>onPage(page+1)}>Siguiente<ChevronRight size={15}/></button></div>}
export default function AdminInventoryPage(){
 const[query,setQuery]=useState(''),[debounced,setDebounced]=useState(''),[stockPage,setStockPage]=useState(1),[movePage,setMovePage]=useState(1);const[stock,setStock]=useState({items:[],total:0,totalPages:1,loading:true,error:''}),[moves,setMoves]=useState({items:[],total:0,totalPages:1,loading:true,error:''});const[editing,setEditing]=useState(null),[newStock,setNewStock]=useState(0),[note,setNote]=useState('Conteo físico / corrección manual'),[saving,setSaving]=useState(false)
 useEffect(()=>{const t=setTimeout(()=>{setDebounced(query.trim());setStockPage(1)},280);return()=>clearTimeout(t)},[query])
 const loadStock=useCallback(async()=>{setStock(x=>({...x,loading:true,error:''}));try{const r=await ops.inventory(stockPage,SIZE,debounced);setStock({items:r.items||[],total:Number(r.total||0),totalPages:Math.max(1,Number(r.totalPages||1)),loading:false,error:''})}catch(e){setStock(x=>({...x,loading:false,error:e.message||'No se pudo cargar el stock.'}))}},[stockPage,debounced])
 const loadMoves=useCallback(async()=>{setMoves(x=>({...x,loading:true,error:''}));try{const r=await ops.stockMovements(movePage,SIZE);setMoves({items:(r.items||[]).map(ops.mapStock),total:Number(r.total||0),totalPages:Math.max(1,Number(r.totalPages||1)),loading:false,error:''})}catch(e){setMoves(x=>({...x,loading:false,error:e.message||'No se pudieron cargar los movimientos.'}))}},[movePage])
 useEffect(()=>{loadStock()},[loadStock]);useEffect(()=>{loadMoves()},[loadMoves]);const open=x=>{setEditing(x);setNewStock(Number(x.stock));setNote('Conteo físico / corrección manual')};const save=async()=>{if(!editing||saving)return;setSaving(true);try{await ops.adjustStock(editing.id,newStock,note);setEditing(null);await Promise.all([loadStock(),loadMoves()])}finally{setSaving(false)}}
 return <><div className="admin-page-header"><div><span className="section-kicker">Inventario</span><h1>Stock y movimientos</h1><p>Control por referencia comercial. Cada color, talle o presentación conserva su propio stock y trazabilidad.</p></div></div>
 <section className="admin-panel inventory-stock-panel"><div className="inventory-panel-head"><div><h2>Stock por variante</h2><p>{stock.total} referencias · 5 por página</p></div><label className="search-box inventory-search"><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar producto, SKU, color o talle…"/></label></div>{stock.error&&<div className="notice-error">{stock.error}</div>}{stock.loading?<div className="screen-loader compact">Cargando stock…</div>:<div className="admin-table-wrap"><table className="admin-table inventory-table-v18"><thead><tr><th>Referencia</th><th>Costo</th><th>Venta</th><th>Físico</th><th>Reservado</th><th>Disponible</th><th>Mínimo</th><th>Estado</th><th></th></tr></thead><tbody>{stock.items.map(x=><tr key={x.id}><td><strong>{x.producto}</strong><small className="table-sub">{x.variante||'Referencia única'} · SKU {x.sku}</small></td><td>{money(x.costo)}</td><td><strong>{money(x.precio)}</strong></td><td>{x.stock}</td><td>{x.reservado}</td><td><strong>{x.disponible}</strong></td><td>{x.stockMinimo}</td><td><span className={`status ${Number(x.disponible)<=Number(x.stockMinimo)?'blocked':'active'}`}>{Number(x.disponible)<=Number(x.stockMinimo)?'Reponer':'Correcto'}</span></td><td><button className="table-action-btn" onClick={()=>open(x)}><SlidersHorizontal size={16}/></button></td></tr>)}</tbody></table></div>}<Pager page={stockPage} total={stock.totalPages} onPage={setStockPage} loading={stock.loading}/></section>
 <section className="admin-panel inventory-movement-panel"><div className="inventory-panel-head"><div><h2>Historial de movimientos</h2><p>{moves.total} movimientos · más recientes primero</p></div><Clock3 size={20}/></div>{moves.error&&<div className="notice-error">{moves.error}</div>}{moves.loading?<div className="screen-loader compact">Cargando movimientos…</div>:<div className="movement-table-wrap"><table className="movement-table-v18"><thead><tr><th>Cambio</th><th>Referencia</th><th>Origen / motivo</th><th>Stock</th><th>Fecha y hora</th></tr></thead><tbody>{moves.items.map(m=><tr key={m.id}><td><div className={`movement-badge-v18 ${m.quantity>=0?'in':'out'}`}>{m.quantity>=0?<TrendingUp size={14}/>:<TrendingDown size={14}/>}<b>{m.quantity>0?'+':''}{m.quantity}</b></div></td><td><strong>{m.productName}</strong><small>{m.variant||'Referencia única'} · SKU {m.sku}</small></td><td><strong>{movementLabel(m.type)}</strong><small>{m.reference||'Sin referencia'}{m.note?` · ${m.note}`:''}</small></td><td><span>{m.stockBefore}</span> <b>→</b> <strong>{m.stockAfter}</strong></td><td><strong>{dateTime(m.createdAt)}</strong></td></tr>)}</tbody></table></div>}<Pager page={movePage} total={moves.totalPages} onPage={setMovePage} loading={moves.loading}/></section>
 {editing&&<div className="modal-backdrop"><div className="modal"><button className="modal-close" onClick={()=>setEditing(null)}>×</button><span className="section-kicker">Ajuste controlado</span><h2>{editing.producto}</h2><p className="modal-subtitle">{editing.variante||'Referencia única'} · SKU {editing.sku}<br/>Stock físico: <b>{editing.stock}</b> · Reservado: <b>{editing.reservado}</b>.</p><label><span>Nuevo stock físico</span><input type="number" min={editing.reservado||0} value={newStock} onChange={e=>setNewStock(e.target.value)}/></label><label><span>Motivo</span><textarea value={note} onChange={e=>setNote(e.target.value)}/></label><button disabled={saving} className="btn btn-primary full-width" onClick={save}>{saving?'Registrando…':'Registrar ajuste'}</button></div></div>}</>}
