import {useEffect,useState} from 'react'
import {ChevronLeft,ChevronRight,CreditCard,Clock3,Eye,Search,ShoppingBag,Store,Truck} from 'lucide-react'
import {Link} from 'react-router-dom'
import {money,dateTime} from '../../utils/commerce'
import {orderStatusLabel,paymentStatusLabel,paymentMethodLabel} from '../../utils/orderWorkflow'
import {operationsRepository as ops} from '../../repositories/operationsRepository'
const PAGE_SIZE=5
function Pager({page,totalPages,onPage,loading}){const nums=Array.from({length:totalPages},(_,i)=>i+1).filter(n=>n===1||n===totalPages||Math.abs(n-page)<=1);return <div className="inventory-pagination orders-pagination"><button disabled={page<=1||loading} onClick={()=>onPage(page-1)}><ChevronLeft size={15}/> Anterior</button><div>{nums.map((n,i)=><span key={n}>{i>0&&n-nums[i-1]>1&&<i>…</i>}<button className={n===page?'active':''} disabled={loading} onClick={()=>onPage(n)}>{n}</button></span>)}</div><button disabled={page>=totalPages||loading} onClick={()=>onPage(page+1)}>Siguiente <ChevronRight size={15}/></button></div>}
export default function AdminOrdersPage(){
 const[query,setQuery]=useState('');const[debounced,setDebounced]=useState('');const[status,setStatus]=useState('all');const[delivery,setDelivery]=useState('all');const[page,setPage]=useState(1);const[state,setState]=useState({items:[],total:0,totalPages:1,summary:{active:0,awaiting:0,shipping:0,paid:0},loading:true,error:''})
 useEffect(()=>{const t=setTimeout(()=>{setDebounced(query.trim());setPage(1)},280);return()=>clearTimeout(t)},[query])
 useEffect(()=>{let live=true;(async()=>{setState(s=>({...s,loading:true,error:''}));try{const r=await ops.orders(page,PAGE_SIZE,debounced,status,delivery);if(!live)return;setState({items:(r.items||[]).map(ops.mapOrder),total:Number(r.total||0),totalPages:Math.max(1,Number(r.totalPages||1)),summary:r.summary||{active:0,awaiting:0,shipping:0,paid:0},loading:false,error:''})}catch(e){if(live)setState(s=>({...s,loading:false,error:e.message||'No se pudieron cargar los pedidos.'}))}})();return()=>{live=false}},[page,debounced,status,delivery])
 const changeStatus=e=>{setStatus(e.target.value);setPage(1)},changeDelivery=e=>{setDelivery(e.target.value);setPage(1)};const k=state.summary
 return <div className="orders-page-v12"><div className="admin-page-header"><div><span className="section-kicker">Operación comercial</span><h1>Pedidos</h1><p>Seguimiento operativo, pagos, reservas, ventas y entregas. Los más recientes aparecen primero.</p></div></div>
 <div className="order-admin-stats order-kpis-v12"><article><Clock3/><div><strong>{k.active}</strong><span>En proceso</span></div></article><article><CreditCard/><div><strong>{k.awaiting}</strong><span>Esperando pago</span></div></article><article><Truck/><div><strong>{k.shipping}</strong><span>Envíos activos</span></div></article><article><ShoppingBag/><div><strong>{k.paid}</strong><span>Pagos acreditados</span></div></article></div>
 <div className="admin-panel orders-toolbar-v12"><div className="order-search-v12"><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar pedido, seguimiento, cliente o teléfono…"/></div><select value={status} onChange={changeStatus}><option value="all">Todos los estados</option>{Object.entries(orderStatusLabel).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select><select value={delivery} onChange={changeDelivery}><option value="all">Todas las entregas</option><option value="pickup">Retiro en sucursal</option><option value="shipping">Envío a domicilio</option></select></div>
 <div className="admin-panel orders-table-panel">{state.error&&<div className="notice-error">{state.error}</div>}<div className="orders-table-wrap"><table className="orders-table-v12"><thead><tr><th>Pedido</th><th>Cliente</th><th>Entrega</th><th>Pago</th><th>Estado pago</th><th>Estado pedido</th><th>Total</th><th></th></tr></thead><tbody>{state.items.map(o=><tr key={o.id}><td><strong>{o.publicCode}</strong><small>{dateTime(o.createdAt)}</small></td><td><strong>{o.customerName||'Sin nombre'}</strong><small>{o.phone||'Sin teléfono'}</small></td><td><span className="table-icon-label">{o.deliveryType==='shipping'?<Truck size={15}/>:<Store size={15}/>} {o.deliveryType==='shipping'?'Envío':'Retiro'}</span></td><td>{paymentMethodLabel[o.paymentMethod]||o.paymentMethod||'—'}</td><td><span className={`order-badge payment-${o.paymentStatus||'pending'}`}>{paymentStatusLabel[o.paymentStatus]||o.paymentStatus||'Pendiente'}</span></td><td><span className={`order-badge order-${o.status}`}>{orderStatusLabel[o.status]||o.status}</span></td><td><strong>{money(o.total)}</strong></td><td><Link className="icon-button table-view-btn" to={`/admin/pedidos/${o.id}`} title="Ver detalle"><Eye size={17}/></Link></td></tr>)}</tbody></table>{state.loading&&<div className="screen-loader compact">Cargando pedidos…</div>}{!state.loading&&!state.items.length&&<div className="orders-empty-v12">No encontramos pedidos con estos filtros.</div>}</div><Pager page={page} totalPages={state.totalPages} onPage={setPage} loading={state.loading}/></div></div>
}
