import { useMemo,useState } from 'react'
import { ArrowLeft, Minus, Plus, Search, ShoppingCart, Trash2 } from 'lucide-react'
import { Link, useNavigate } from 'react-router-dom'
import { useAppData } from '../../context/AppDataContext'
import { money } from '../../utils/commerce'

const variantName=v=>[v.color,v.size,v.name].filter(Boolean).join(' · ')||'Referencia única'
export default function AdminPointOfSalePage(){
 const {data,loading,confirmSale}=useAppData();const navigate=useNavigate();const [query,setQuery]=useState('');const [cart,setCart]=useState([]);const [customer,setCustomer]=useState('');const [payment,setPayment]=useState('Efectivo');const [message,setMessage]=useState('');const [discountType,setDiscountType]=useState('none');const [discountValue,setDiscountValue]=useState(0)
 const references=useMemo(()=>{const q=query.trim().toLowerCase();return (data?.products||[]).filter(p=>p.active).flatMap(p=>(p.variants||[]).filter(v=>v.active!==false&&v.available!==false&&Number(v.availableStock)>0).map(v=>({productId:p.id,variantId:v.id,productName:p.name,variantName:variantName(v),sku:v.sku,barcode:v.barcode,brand:p.brand,image:v.image||p.image,price:Number(v.price||0),stock:Number(v.availableStock||0)}))).filter(r=>!q||`${r.productName} ${r.variantName} ${r.sku} ${r.barcode||''} ${r.brand||''}`.toLowerCase().includes(q))},[data,query])
 if(loading)return <div className="screen-loader">Cargando…</div>
 const add=r=>setCart(c=>{const f=c.find(x=>x.variantId===r.variantId);return f?c.map(x=>x.variantId===r.variantId?{...x,quantity:Math.min(r.stock,x.quantity+1)}:x):[...c,{productId:r.productId,variantId:r.variantId,productName:r.productName,variantName:r.variantName,sku:r.sku,stock:r.stock,quantity:1,unitPrice:r.price}]})
 const update=(variantId,q)=>setCart(c=>{const row=c.find(x=>x.variantId===variantId);if(!row)return c;return q<=0?c.filter(x=>x.variantId!==variantId):c.map(x=>x.variantId===variantId?{...x,quantity:Math.min(row.stock,q)}:x)})
 const grossTotal=cart.reduce((s,x)=>s+x.quantity*x.unitPrice,0);const discountAmount=discountType==='percent'?Math.min(grossTotal,grossTotal*Math.min(100,Number(discountValue)||0)/100):discountType==='amount'?Math.min(grossTotal,Number(discountValue)||0):0;const total=grossTotal-discountAmount
 const submit=async()=>{if(!cart.length)return;setMessage('');const result=await confirmSale({source:'pos',customerName:customer||'Venta mostrador',paymentMethod:payment,items:cart.map(x=>({productId:x.productId,variantId:x.variantId,quantity:x.quantity,unitPrice:x.unitPrice})),discountType,discountValue:Number(discountValue)||0});if(!result.ok){setMessage(result.error);return}navigate(`/admin/ventas/${result.sale.id}`,{state:{created:true}})}
 return <><div className="admin-page-header compact-page-header"><div><Link className="back-link" to="/admin/ventas/historial"><ArrowLeft size={15}/> Volver al historial</Link><span className="section-kicker">Punto de venta</span><h1>Nueva venta presencial</h1><p>Cada tarjeta representa una variante vendible real. El stock mostrado es el disponible, descontando reservas de pedidos web.</p></div></div>{message&&<div className="notice-error">{message}</div>}
 <div className="pos-layout"><section className="admin-panel"><label className="search-box"><Search size={18}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar producto, variante, SKU, código o marca…"/></label><div className="pos-reference-count">{references.length} referencias disponibles</div><div className="pos-product-grid">{references.map(r=><button className="pos-product" key={r.variantId} onClick={()=>add(r)}><img src={r.image} alt=""/><div><small>{r.sku}</small><strong>{r.productName}</strong><em>{r.variantName}</em><span>{money(r.price)} · Disponible {r.stock}</span></div><Plus size={18}/></button>)}</div></section><aside className="admin-panel pos-cart"><div className="panel-title-row"><div><h2>Venta actual</h2><p>{cart.reduce((s,x)=>s+x.quantity,0)} unidades · {cart.length} referencias</p></div><ShoppingCart size={22}/></div><div className="pos-lines">{!cart.length&&<div className="empty-agenda">Seleccioná una variante para comenzar.</div>}{cart.map(row=><article key={row.variantId}><div><strong>{row.productName}</strong><small>{row.variantName} · {row.sku}<br/>{money(row.unitPrice)} c/u</small></div><div className="qty-control"><button onClick={()=>update(row.variantId,row.quantity-1)}><Minus size={14}/></button><strong>{row.quantity}</strong><button onClick={()=>update(row.variantId,row.quantity+1)}><Plus size={14}/></button></div><strong>{money(row.quantity*row.unitPrice)}</strong><button className="danger-icon" onClick={()=>update(row.variantId,0)}><Trash2 size={15}/></button></article>)}</div><label><span>Cliente (opcional)</span><input value={customer} onChange={e=>setCustomer(e.target.value)} placeholder="Venta mostrador"/></label><label><span>Medio de pago</span><select value={payment} onChange={e=>setPayment(e.target.value)}><option>Efectivo</option><option>Transferencia</option><option>Tarjeta</option><option>Mercado Pago</option><option>Otro</option></select></label><div className="discount-box"><label><span>Descuento</span><select value={discountType} onChange={e=>setDiscountType(e.target.value)}><option value="none">Sin descuento</option><option value="percent">Por porcentaje (%)</option><option value="amount">Por monto ($)</option></select></label>{discountType!=='none'&&<label><span>{discountType==='percent'?'Porcentaje':'Monto'}</span><input type="number" min="0" max={discountType==='percent'?100:undefined} value={discountValue} onChange={e=>setDiscountValue(e.target.value)}/></label>}</div><div className="totals-breakdown"><span>Subtotal <b>{money(grossTotal)}</b></span>{discountAmount>0&&<span className="discount-line">Descuento <b>- {money(discountAmount)}</b></span>}<div className="pos-total"><span>Total final</span><strong>{money(total)}</strong></div></div><button className="btn btn-primary full-width" disabled={!cart.length} onClick={submit}>Confirmar venta</button></aside></div></>
}
