import { useMemo,useState } from 'react'
import { AlertTriangle, Boxes, Search, SlidersHorizontal } from 'lucide-react'
import { useAppData } from '../../context/AppDataContext'
import { money,dateTime,movementLabel } from '../../utils/commerce'

export default function AdminInventoryPage(){
 const {data,loading,adjustStock}=useAppData(); const [query,setQuery]=useState(''); const [editing,setEditing]=useState(null); const [newStock,setNewStock]=useState(0); const [note,setNote]=useState('Conteo físico / corrección manual')
 const products=useMemo(()=>data?.products.filter(x=>!query||`${x.name} ${x.sku}`.toLowerCase().includes(query.toLowerCase()))||[],[data,query]); if(loading)return <div className="screen-loader">Cargando…</div>
 const costValue=data.products.reduce((s,p)=>s+p.stock*(p.costPrice||0),0), saleValue=data.products.reduce((s,p)=>s+p.stock*p.price,0), low=data.products.filter(p=>p.trackStock!==false&&p.stock<=p.minStock)
 const open=p=>{setEditing(p);setNewStock(p.stock)}; const save=async()=>{await adjustStock(editing.id,newStock,note);setEditing(null)}
 return <><div className="admin-page-header"><div><span className="section-kicker">Inventario</span><h1>Stock y movimientos</h1><p>Trazabilidad de cada entrada, salida y corrección. El stock no se modifica silenciosamente.</p></div></div><div className="inventory-stats"><article><Boxes size={20}/><strong>{data.products.reduce((s,p)=>s+p.stock,0)}</strong><span>Unidades en stock</span></article><article><strong>{money(costValue)}</strong><span>Capital a costo</span></article><article><strong>{money(saleValue)}</strong><span>Valor potencial de venta</span></article><article className={low.length?'warning-card':''}><AlertTriangle size={20}/><strong>{low.length}</strong><span>Productos en stock mínimo</span></article></div>
 <div className="admin-panel"><label className="search-box admin-search"><Search size={18}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar producto o SKU…"/></label><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Producto</th><th>Costo</th><th>Venta</th><th>Stock</th><th>Mínimo</th><th>Estado</th><th>Ajuste</th></tr></thead><tbody>{products.map(p=><tr key={p.id}><td data-label="Producto"><strong>{p.name}</strong><small className="table-sub">{p.sku}</small></td><td data-label="Costo">{money(p.costPrice)}</td><td data-label="Venta">{money(p.price)}</td><td data-label="Stock"><strong>{p.stock}</strong></td><td data-label="Mínimo">{p.minStock}</td><td data-label="Estado"><span className={`status ${p.stock<=p.minStock?'blocked':'active'}`}>{p.stock<=p.minStock?'Reponer':'Correcto'}</span></td><td data-label="Ajuste"><button className="btn btn-secondary compact-btn" onClick={()=>open(p)}><SlidersHorizontal size={15}/> Ajustar</button></td></tr>)}</tbody></table></div></div>
 <div className="admin-panel sales-history"><h2>Historial de movimientos</h2><div className="movement-list">{(data.stockMovements||[]).slice().sort((a,b)=>new Date(b.createdAt)-new Date(a.createdAt)).slice(0,30).map(m=><article key={m.id}><div className={`movement-qty ${m.quantity>0?'in':'out'}`}>{m.quantity>0?'+':''}{m.quantity}</div><div><strong>{m.productName}</strong><span>{movementLabel(m.type)} · {m.reference}</span><small>{dateTime(m.createdAt)} · Stock final {m.stockAfter} · {m.note}</small></div></article>)}</div></div>
 {editing&&<div className="modal-backdrop"><div className="modal"><button className="modal-close" onClick={()=>setEditing(null)}>×</button><span className="section-kicker">Ajuste controlado</span><h2>{editing.name}</h2><p className="modal-subtitle">Stock registrado: {editing.stock}. El sistema guardará la diferencia como movimiento.</p><label><span>Nuevo stock físico</span><input type="number" min="0" value={newStock} onChange={e=>setNewStock(e.target.value)}/></label><label><span>Motivo</span><textarea value={note} onChange={e=>setNote(e.target.value)}/></label><button className="btn btn-primary full-width" onClick={save}>Registrar ajuste</button></div></div>}
 </>
}
