import { useMemo,useState } from 'react'
import { ArrowLeft, Minus, Plus, Search, ShoppingCart, Trash2 } from 'lucide-react'
import { Link, useNavigate } from 'react-router-dom'
import { useAppData } from '../../context/AppDataContext'
import { money } from '../../utils/commerce'

export default function AdminPointOfSalePage(){
 const {data,loading,confirmSale}=useAppData(); const navigate=useNavigate(); const [query,setQuery]=useState(''); const [cart,setCart]=useState([]); const [customer,setCustomer]=useState(''); const [payment,setPayment]=useState('Efectivo'); const [message,setMessage]=useState(''); const [discountType,setDiscountType]=useState('none'); const [discountValue,setDiscountValue]=useState(0)
 const products=useMemo(()=>data?.products.filter(x=>x.active&&x.stock>0).filter(x=>!query||`${x.name} ${x.sku} ${x.brand}`.toLowerCase().includes(query.toLowerCase()))||[],[data,query]); if(loading)return <div className="screen-loader">Cargando…</div>
 const add=p=>setCart(c=>{const f=c.find(x=>x.productId===p.id);return f?c.map(x=>x.productId===p.id?{...x,quantity:Math.min(p.stock,x.quantity+1)}:x):[...c,{productId:p.id,quantity:1,unitPrice:p.price}]}); const update=(id,q)=>{const p=data.products.find(x=>x.id===id);setCart(c=>q<=0?c.filter(x=>x.productId!==id):c.map(x=>x.productId===id?{...x,quantity:Math.min(p.stock,q)}:x))}
 const grossTotal=cart.reduce((s,x)=>s+x.quantity*x.unitPrice,0); const discountAmount=discountType==='percent'?Math.min(grossTotal,grossTotal*Math.min(100,Number(discountValue)||0)/100):discountType==='amount'?Math.min(grossTotal,Number(discountValue)||0):0; const total=grossTotal-discountAmount
 const submit=async()=>{if(!cart.length)return;const result=await confirmSale({source:'pos',customerName:customer||'Venta mostrador',paymentMethod:payment,items:cart,discountType,discountValue:Number(discountValue)||0});if(!result.ok){setMessage(result.error);return}navigate(`/admin/ventas/${result.sale.id}`,{state:{created:true}})}
 return <><div className="admin-page-header compact-page-header"><div><Link className="back-link" to="/admin/ventas"><ArrowLeft size={15}/> Volver al historial</Link><span className="section-kicker">Punto de venta</span><h1>Nueva venta presencial</h1><p>El descuento se registra sobre la operación y se distribuye proporcionalmente para conocer el precio real vendido por producto.</p></div></div>{message&&<div className="notice-error">{message}</div>}
 <div className="pos-layout"><section className="admin-panel"><label className="search-box"><Search size={18}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar por producto, SKU o marca…"/></label><div className="pos-product-grid">{products.map(p=><button className="pos-product" key={p.id} onClick={()=>add(p)}><img src={p.image} alt=""/><div><small>{p.sku}</small><strong>{p.name}</strong><span>{money(p.price)} · Stock {p.stock}</span></div><Plus size={18}/></button>)}</div></section><aside className="admin-panel pos-cart"><div className="panel-title-row"><div><h2>Venta actual</h2><p>{cart.reduce((s,x)=>s+x.quantity,0)} unidades</p></div><ShoppingCart size={22}/></div><div className="pos-lines">{!cart.length&&<div className="empty-agenda">Seleccioná productos para comenzar.</div>}{cart.map(row=>{const p=data.products.find(x=>x.id===row.productId);return <article key={row.productId}><div><strong>{p.name}</strong><small>{money(row.unitPrice)} c/u</small></div><div className="qty-control"><button onClick={()=>update(row.productId,row.quantity-1)}><Minus size={14}/></button><strong>{row.quantity}</strong><button onClick={()=>update(row.productId,row.quantity+1)}><Plus size={14}/></button></div><strong>{money(row.quantity*row.unitPrice)}</strong><button className="danger-icon" onClick={()=>update(row.productId,0)}><Trash2 size={15}/></button></article>})}</div><label><span>Cliente (opcional)</span><input value={customer} onChange={e=>setCustomer(e.target.value)} placeholder="Venta mostrador"/></label><label><span>Medio de pago</span><select value={payment} onChange={e=>setPayment(e.target.value)}><option>Efectivo</option><option>Transferencia</option><option>Tarjeta</option><option>Mercado Pago</option><option>Otro</option></select></label><div className="discount-box"><label><span>Descuento</span><select value={discountType} onChange={e=>setDiscountType(e.target.value)}><option value="none">Sin descuento</option><option value="percent">Por porcentaje (%)</option><option value="amount">Por monto ($)</option></select></label>{discountType!=='none'&&<label><span>{discountType==='percent'?'Porcentaje':'Monto'}</span><input type="number" min="0" max={discountType==='percent'?100:undefined} value={discountValue} onChange={e=>setDiscountValue(e.target.value)}/></label>}</div><div className="totals-breakdown"><span>Subtotal <b>{money(grossTotal)}</b></span>{discountAmount>0&&<span className="discount-line">Descuento <b>- {money(discountAmount)}</b></span>}<div className="pos-total"><span>Total final</span><strong>{money(total)}</strong></div></div><button className="btn btn-primary full-width" disabled={!cart.length} onClick={submit}>Confirmar venta</button></aside></div></>
}
