import { useMemo,useState } from 'react'
import { Edit3, Eye, EyeOff, Plus, Search, X } from 'lucide-react'
import { useAppData } from '../../context/AppDataContext'
const empty={id:0,name:'',taxId:'',phone:'',email:'',notes:'',active:true,defaultMarkupPercent:0}
export default function AdminSuppliersPage(){
 const {data,loading,saveSupplier,toggleSupplier}=useAppData(); const [query,setQuery]=useState(''); const [editing,setEditing]=useState(undefined); const [form,setForm]=useState(empty)
 const list=useMemo(()=>data?.suppliers?.filter(x=>!query||`${x.name} ${x.taxId} ${x.phone}`.toLowerCase().includes(query.toLowerCase()))||[],[data,query]); if(loading)return <div className="screen-loader">Cargando…</div>
 const open=item=>{setEditing(item||null);setForm(item?{...empty,...item}:empty)}; const submit=async e=>{e.preventDefault();await saveSupplier({...form,defaultMarkupPercent:Number(form.defaultMarkupPercent)||0});setEditing(undefined)}
 return <><div className="admin-page-header"><div><span className="section-kicker">Abastecimiento y precios</span><h1>Proveedores</h1><p>Cada proveedor puede tener un porcentaje base que se incorpora a la formación automática del precio.</p></div><button className="btn btn-primary" onClick={()=>open(null)}><Plus size={17}/> Nuevo proveedor</button></div><label className="search-box admin-search"><Search size={18}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar proveedor…"/></label><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Proveedor</th><th>CUIT</th><th>Contacto</th><th>% base</th><th>Estado</th><th>Acciones</th></tr></thead><tbody>{list.map(x=><tr key={x.id}><td><strong>{x.name}</strong></td><td>{x.taxId||'—'}</td><td><div className="stack-small"><span>{x.phone||'—'}</span><small>{x.email}</small></div></td><td><strong>{Number(x.defaultMarkupPercent||0)}%</strong></td><td><span className={`status ${x.active?'active':'inactive'}`}>{x.active?'Activo':'Inactivo'}</span></td><td><div className="table-actions"><button onClick={()=>open(x)}><Edit3 size={16}/></button><button onClick={()=>toggleSupplier(x.id)}>{x.active?<EyeOff size={16}/>:<Eye size={16}/>}</button></div></td></tr>)}</tbody></table></div>
 {editing!==undefined&&<div className="modal-backdrop"><div className="modal"><button className="modal-close" onClick={()=>setEditing(undefined)}><X size={20}/></button><span className="section-kicker">Proveedor</span><h2>{form.id?'Editar proveedor':'Nuevo proveedor'}</h2><form className="editor-form" onSubmit={submit}><label><span>Razón social / nombre</span><input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><div className="form-grid"><label><span>CUIT</span><input value={form.taxId} onChange={e=>setForm({...form,taxId:e.target.value})}/></label><label><span>Teléfono</span><input value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></label></div><label><span>Porcentaje base proveedor</span><div className="percent-input"><input type="number" step="0.01" value={form.defaultMarkupPercent} onChange={e=>setForm({...form,defaultMarkupPercent:e.target.value})}/><span>%</span></div><small className="field-hint">Se aplica antes del porcentaje de marca y del producto.</small></label><label><span>Email</span><input type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label><label><span>Notas</span><textarea value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></label><button className="btn btn-primary full-width">Guardar</button></form></div></div>}
 </>
}
