import { useState } from 'react'
import { ArrowLeft,CheckCircle2,Clock3,CreditCard,MapPin,PackageCheck,Phone,Mail,Store,Truck,UserRound,XCircle,WalletCards,ReceiptText,Copy,MessageCircle } from 'lucide-react'
import { Link,useParams } from 'react-router-dom'
import { useAppData } from '../../context/AppDataContext'
import { money,dateTime } from '../../utils/commerce'
import { orderStatusLabel,paymentStatusLabel,paymentMethodLabel,nextOperationalStatus,canCancelOrder,canConfirmPayment,paymentActionLabel } from '../../utils/orderWorkflow'

const actionLabel={confirmed:'Confirmar disponibilidad',awaiting_payment:'Pasar a espera de pago',pending_shipment:'Pasar a pendiente de envío',ready_for_pickup:'Marcar listo para retirar',shipped:'Confirmar envío',completed:'Marcar pedido completado'}
const BANK={cbu:'4530000800014157456427',alias:'RC.REPUESTOS.NX',account:'1415745642',holder:'Bruno Julian Carrizo',cuil:'20422170503',bank:'Naranja X'}
export default function AdminOrderDetailPage(){
 const {id}=useParams();const{data,loading,advanceOrder,cancelOrder,confirmOrderPayment}=useAppData();const[message,setMessage]=useState('');const[working,setWorking]=useState(false)
 if(loading)return <div className="screen-loader">Cargando pedido…</div>
 const o=(data.orders||[]).find(x=>String(x.id)===String(id));if(!o)return <div className="admin-panel"><h2>Pedido no encontrado</h2><Link to="/admin/pedidos">Volver a pedidos</Link></div>
 const next=nextOperationalStatus(o);const address=[o.shippingAddress?.street,o.shippingAddress?.number].filter(Boolean).join(' ')
 const run=async fn=>{if(working)return;setWorking(true);setMessage('');try{const r=await fn();if(r&&!r.ok)setMessage(r.error)}finally{setWorking(false)}}
 const advance=()=>run(()=>advanceOrder(o.id));const cancel=()=>run(()=>cancelOrder(o.id));const confirmPayment=()=>run(()=>confirmOrderPayment(o.id))
 const trackingUrl=`${window.location.origin}/seguimiento/${encodeURIComponent(o.trackingCode||'')}`
 const copyTracking=async()=>{await navigator.clipboard?.writeText(trackingUrl);setMessage('Enlace de seguimiento copiado.')}
 const trackingWhatsapp=`https://wa.me/${String(o.phone||'').replace(/\D/g,'')}?text=${encodeURIComponent(`Hola ${o.customerName||''}. Podés seguir el estado de tu pedido ${o.publicCode} de RC Repuestos y Accesorios desde este enlace: ${trackingUrl}`)}`
 return <div className="order-detail-v12 production-order-detail">
  <div className="detail-top-v12"><Link className="btn btn-secondary" to="/admin/pedidos"><ArrowLeft size={16}/> Pedidos</Link><div className="detail-top-actions-v12">{canCancelOrder(o)&&<button disabled={working} className="btn btn-secondary danger-outline" onClick={cancel}><XCircle size={16}/> Cancelar pedido</button>}{next&&<button disabled={working} className="btn btn-primary" onClick={advance}><CheckCircle2 size={16}/> {actionLabel[next]||'Continuar pedido'}</button>}{o.trackingCode&&<button className="btn btn-secondary" onClick={copyTracking}><Copy size={16}/> Copiar seguimiento</button>}{o.trackingCode&&<a className="btn btn-secondary" href={trackingWhatsapp} target="_blank" rel="noreferrer"><MessageCircle size={16}/> Enviar seguimiento</a>}{o.saleId&&<Link className="btn btn-secondary" to={`/admin/ventas/${o.saleId}`}><ReceiptText size={16}/> Ver venta {o.saleNumber}</Link>}</div></div>
  <div className="admin-page-header order-detail-heading"><div><span className="section-kicker">Detalle del pedido</span><h1>{o.publicCode}</h1><p>Recibido {dateTime(o.createdAt)} · seguimiento {o.trackingCode}</p></div><div className="detail-status-stack"><span className={`order-badge order-${o.status}`}>{orderStatusLabel[o.status]||o.status}</span><span className={`order-badge payment-${o.paymentStatus}`}>{paymentStatusLabel[o.paymentStatus]||o.paymentStatus}</span>{o.saleId&&<span className="order-badge payment-approved">Venta registrada</span>}</div></div>
  {message&&<div className="admin-inline-message">{message}</div>}
  <div className="order-detail-grid-v12"><main className="detail-main-v12">
   <section className="admin-panel detail-section-v12"><div className="detail-section-title"><PackageCheck/><div><h2>Productos</h2><p>Detalle comercial asentado en el pedido.</p></div></div><div className="detail-products-v12">{o.items.map(i=><article key={i.productId}><div><strong>{i.name}</strong><small>{i.sku} · {i.quantity} × {money(i.unitPrice)}</small></div><strong>{money(i.subtotal)}</strong></article>)}</div><div className="detail-totals-v12"><span>Subtotal <b>{money(o.grossTotal)}</b></span>{o.discountAmount>0&&<span>Descuento <b>- {money(o.discountAmount)}</b></span>}<strong>Total productos <b>{money(o.total)}</b></strong>{o.deliveryType==='shipping'&&<span className="shipping-total-note">Envío <b>A coordinar con el cliente</b></span>}</div></section>
   <section className="admin-panel detail-section-v12"><div className="detail-section-title">{o.deliveryType==='shipping'?<Truck/>:<Store/>}<div><h2>{o.deliveryType==='shipping'?'Envío a domicilio':'Retiro en sucursal'}</h2><p>{o.deliveryType==='shipping'?'Domicilio asentado al momento de realizar el pedido.':'El cliente retirará en RC Repuestos y Accesorios.'}</p></div></div>{o.deliveryType==='shipping'?<div className="address-card-v12"><MapPin/><div><strong>{address||'Dirección sin completar'}</strong><span>{o.shippingAddress?.city||'—'} · CP {o.shippingAddress?.postalCode||'—'}</span><span>{o.shippingAddress?.province||'—'}</span>{o.shippingAddress?.notes&&<p>{o.shippingAddress.notes}</p>}<small className="shipping-cost-admin">Costo de envío: a coordinar con el cliente.</small></div></div>:<div className="address-card-v12"><Store/><div><strong>RC Repuestos y Accesorios</strong><span>Retiro coordinado con el comercio.</span></div></div>}</section>
   {o.paymentMethod==='transfer'&&o.status!=='received'&&<section className="admin-panel detail-section-v12"><div className="detail-section-title"><WalletCards/><div><h2>Transferencia bancaria</h2><p>Datos habilitados luego de confirmar la disponibilidad.</p></div></div><div className="bank-data-grid admin-bank-grid"><span><small>CBU</small><b>{BANK.cbu}</b></span><span><small>Alias</small><b>{BANK.alias}</b></span><span><small>Caja de ahorro</small><b>{BANK.account}</b></span><span><small>Titular</small><b>{BANK.holder}</b></span><span><small>CUIL</small><b>{BANK.cuil}</b></span><span><small>Entidad</small><b>{BANK.bank}</b></span></div></section>}
  </main>
  <aside className="detail-side-v12">
   <section className="admin-panel detail-section-v12"><div className="detail-section-title"><UserRound/><div><h2>Cliente</h2><p>Datos de contacto.</p></div></div><div className="detail-info-list"><span><UserRound size={16}/><b>{o.customerName||'—'}</b></span><span><Phone size={16}/>{o.phone||'—'}</span><span><Mail size={16}/>{o.email||'No informado'}</span></div>{o.notes&&<div className="detail-note-v12"><small>Observaciones</small><p>{o.notes}</p></div>}</section>
   <section className="admin-panel detail-section-v12"><div className="detail-section-title"><CreditCard/><div><h2>Pago y venta</h2><p>La acreditación genera la venta, descuenta stock y registra el ingreso en caja una única vez.</p></div></div><div className="detail-info-pairs"><span>Método <b>{paymentMethodLabel[o.paymentMethod]||o.paymentMethod||'—'}</b></span><span>Estado <b>{paymentStatusLabel[o.paymentStatus]||o.paymentStatus}</b></span>{o.paymentExternalId&&<span>ID externo <b>{o.paymentExternalId}</b></span>}<span>Total productos <b>{money(o.total)}</b></span></div>{canConfirmPayment(o)&&<button disabled={working} className="btn btn-primary full-action" onClick={confirmPayment}><CheckCircle2 size={16}/> {paymentActionLabel(o)}</button>}{o.saleId&&<div className="sale-registered-card"><CheckCircle2/><div><strong>Venta registrada</strong><span>{o.saleNumber} · {dateTime(o.saleCompletedAt)}</span></div></div>}</section>
   <section className="admin-panel detail-section-v12"><div className="detail-section-title"><PackageCheck/><div><h2>Proceso del pedido</h2><p>Los estados avanzan únicamente en el orden operativo permitido.</p></div></div><div className="workflow-stack">{(o.statusHistory||[{status:o.status,at:o.createdAt}]).map((h,i)=><div key={`${h.status}-${i}`} className="workflow-row done"><i/><div><strong>{orderStatusLabel[h.status]||h.label||'Pedido recibido'}</strong><small>{dateTime(h.at)}</small></div></div>)}</div>{next&&<button disabled={working} className="btn btn-primary full-action" onClick={advance}>{actionLabel[next]||'Continuar pedido'}</button>}{o.status==='awaiting_payment'&&o.paymentStatus!=='approved'&&<div className="detail-note-v12"><small>Siguiente paso</small><p>Registrar la acreditación del pago para continuar con la entrega.</p></div>}</section>
   <section className="admin-panel detail-section-v12"><div className="detail-section-title"><Clock3/><div><h2>Cierre comercial</h2><p>El pedido y la venta mantienen trazabilidad independiente.</p></div></div>{o.saleId?<><div className="sale-registered-card"><ReceiptText/><div><strong>{o.saleNumber}</strong><span>Ingreso asentado en Caja · stock actualizado</span></div></div><Link className="btn btn-secondary full-action" to={`/admin/ventas/${o.saleId}`}>Ver detalle de la venta</Link></>:<p className="closing-copy">La venta se generará automáticamente al confirmar la acreditación del pago.</p>}</section>
  </aside></div>
 </div>
}
